### ISSUE TITLE
Screen doesn't resize/scroll on keyboard hide/show

### ISSUE THREAD

**Issue by joeshaw** [blinksh/blink#101]
Blink 0.916.26.

This is related to #80 and #97, but I'm not sure if it's exactly the same issue.  Unlike #80, this is with the stock keyboard.  Unlike #97, this is in portrait mode.

When mosh'ed into a machine running irssi inside of tmux, initially the viewport is the area between the top of the screen and the top of the keyboard (roughly 20 lines).  If you perform some action which dismisses the keyboard, the viewport is resized to the entire display area (roughly 34 lines).  When you perform an action to slide the keyboard back in, the viewport does not resize and the bottom part is hidden behind the keyboard.

While it's possible to scroll back down to the bottom of the screen, it never seems to resize to the correct size.

**Comment by carloscabanero** [comment]
Thanks for your thorough testing with the iPhone! Unfortunately I cannot replicate this one :( When you say "an action" to make the keyboard disappear, I guess you just do a long press? And then tapping again for it to appear? I can see the messages sending perfectly and adapting even if I have tmux open. I wonder if having both keyboards is causing any issue... Also, is this iOS 9.3 or 10?

Thanks again!!

**Comment by joeshaw** [comment]
Correct, doing a long press to hide the keyboard and then tapping again to bring it back up.  I can attach a video if that'd be helpful.  I only have the stock keyboard and the emoji keyboard enabled right now (with the stock keyboard being the one displayed).

I'm connecting with a command-line like `mosh example.com -- tmux attach -d`

Running on an iPhone 6S with iOS 9.3.4.

**Comment by joeshaw** [comment]
A fairly simple test: in a terminal, run `while true; do tput lines; sleep 2; done`.  Initially for me it's 21 lines, when I dismiss the keyboard it goes to 35, when I tap again the keyboard comes up, it remains 35 (and doesn't scroll to the bottom).

**Comment by carloscabanero** [comment]
Still nothing :( I think the previous ones and this one must be related. I will start by solving those and see if this also gets fixed. Worst case scenario we will buy you a new phone :smile:

**Comment by joeshaw** [comment]
I wonder if it's something to do with tmux, because I'm not able to reproduce it outside of tmux.

**Comment by joeshaw** [comment]
I may have spoken too soon!  I just got it to happen outside of tmux as well.  I think it might have something to do with the amount of scrollback, so make sure you have plenty of previous output on the terminal before you try.

**Comment by carloscabanero** [comment]
I run it inside and outside tmux with same result. I'm pretty sure this could be related to the new way of triggering a resize on the terminal.

**Comment by carloscabanero** [comment]
Hmmmm... What I can see is that some of the lines get lost during the resize, but the cursor always stays at the end of the screen, and the column number changes properly. Tried on the simulator too. Anyway, will try to clean up the other two issues and hopefully will help with this one too.

**Comment by strowger** [comment]
I'm having this trouble as well. It's frustrating.

It only started to occur yesterday for me even though I've been using the current blink release every day since it was first made available. I am unsure why it has changed for me. I use the Swiftkey keyboard - which hasn't updated for some weeks.

If I use swifkey then I have this problem whenever I switch away from the blink app and return.

With the system keyboard, switching away from the app and back doesn't trigger the problem, but hiding the keyboard and then bringing it back does replicate the problem.

**Comment by carloscabanero** [comment]
This was a tricky one and definitely related to #80, I could finally replicate it and hopefully solve it. There is a very strange race condition when performing a resize that is only triggered in specific cases once in a while, it happens more often with custom keyboards. The problem here is with how the WKWebView works internally with its viewports, the layout might happen multiple times and sometimes not the right size arrives as an event. The cure is to basically trigger it ourselves to make sure everything is as it should.

It works perfectly right now in my tests, I tried to follow the event chain and keep changes to a minimum. If you guys still experience strange behaviour I will take care of the full events chain myself during a resize.

A new version is coming out today with big changes and I this will be included, I will keep the issue open, let me know how it goes and once you give me the thumbs up I will proceed to close it.

**Comment by strowger** [comment]
Sorry to pester - I can't see the new version in hockey, do I need to do something or refresh something?

**Comment by yury** [comment]
@strowger what build do you have there?

**Comment by carloscabanero** [comment]
No worries at all. I'm actually closing up the keyboard configuration and it was too good to leave outside the build. So there was no build yesterday, but it will be up today :)

**Comment by strowger** [comment]
Blink: v0.916.26. Aug 16 2016

**Comment by strowger** [comment]
I used the previous release intensively for several days before encountering the problem, so I'm reluctant to say 100% for certain that it is now fixed - but it does appear to be.

Thank you - nice work.

**Comment by joeshaw** [comment]
Things are working great for me now, after a couple of weeks of banging on this.  Thank you.

**Comment by strowger** [comment]
Agreed. Haven't had any trouble since the version with the fix.

**Comment by carloscabanero** [comment]
Awesome! This was a tricky one because we are doing some realignments to avoid any type of pollution in the window. Glad it worked :)
