### ISSUE TITLE
Slight oddity with ctrl-space fix

### ISSUE THREAD

**Issue by efroemling** [blinksh/blink#1033]
I just got the update which makes ctrl-space work again by adding it as a custom shortcut. I am definitely rejoicing :)

One slight oddity however: generally in Emacs I select text by hitting control space and then hitting n, p, f, or b while still holding down ~~space~~ control. It seems that this doesn't work with the new fix; I have to let go of control and then press it again before typing the other characters.

I'm curious if this is a fixable issue or if it is an inherent limitation of whatever magic is being used to override the OS' ctrl-space binding.

A big thanks for the overall ctrl-space fix though! This issue is slightly annoying but an order of magnitude better than having the emoji picker pop up constantly when I would forget to use my weird workaround shortcut.

**Comment by yury** [comment]
> while still holding space.

Space or ctrl?

**Comment by efroemling** [comment]
Sorry, I mistyped; while still holding ctrl.

**Comment by efroemling** [comment]
So: press control, press/release space, press/release n, release control -> normally I would get a line selected, but instead this types an 'n'.

**Comment by yury** [comment]
Yep, I got it. I will look. 

As a workaround, for now, you can map :

- ctrl+b to hex 02
- ctrl+n to hex 0e

Etc (you can look codes with `showkey` command)

**Comment by bs** [comment]
Rejoice, indeed! <3

**Comment by treyharris** [comment]
@yury wrote:
> As a workaround, for now, you can map :
> 
> * ctrl+b to hex 02
> * ctrl+n to hex 0e
> 
> Etc (you can look codes with `showkey` command)

It appears if you want the hex thing to work you have to set it for _every_ control key; otherwise, the problem just propagates to whatever the first ctrl key you use after using one redefined in “Custom presses”. (So, in other words, if you add <kbd>C-SPC</kbd>, <kbd>C-b</kbd>, and <kbd>C-n</kbd> as above, then <kbd>C-SPC C-b C-n</kbd> works great, but then if you type some stuff and type <kbd>C-a</kbd>, you get a plain `a` instead.

Another weirdness: if you enter a hex code, you _must_ press <kbd>RET</kbd> after entering the hex code; otherwise, though the GUI sheet will appear to show a successful setting of, say, ⌃B to Hex 02, instead <kbd>C-b</kbd> gets swallowed; if you exit the Config sheet and reopen it, though, it “correctly” shows ⌃B as pressing an empty hex code.

**Comment by geoffp** [comment]
I reported the same issue on #782. I’ll try the hex-code workaround as well and see how it goes.

**Comment by geoffp** [comment]
Mapping:
 `^A` -> `01`
 `^E` -> `05`
 `^G` -> `07`
 `^N` -> `0E`
 `^P` -> `10`
`^[space]` -> `^[space]`

more or less gets my Emacs text-selection flow back. It’s definitely still more in the category of “extensively worked around” rather than “fixed”, but I’m glad it works. Thanks @yury. Hopefully there’s a cleaner fix for this (maybe like the iSH one pointed to in #782), but ideally, Apple would just allow us to turn off the ctrl-space shortcut, I suppose.

**Comment by roangel** [comment]
Is this ctrl + space problem fixed for good? If so I’ll undoubtedly buy the app

**Comment by geoffp** [comment]
It’s not. I’ve made hex-codes for almost every keystroke, and it still feels unstable, unfortunately. It’s usable, but does the wrong thing seemingly at random.

**Comment by treyharris** [comment]
I believe this can be closed. I was going through my old issues and noticed this from #782 — I just tried it with the ⌃␣ custom press and had no problem going straight from ⌃␣ to ⌃N, ⌃B, etc.

**Comment by geoffp** [comment]
It’s been stable for me too! Thanks @yury!

**Comment by raamdev** [comment]
I was running into the issue with the Emoji keyboard popping up again for ctrl + space, even with the custom press fix in place. What eventually got it working again was removing the Emoji keyboard from Settings -> General -> Keyboard -> Keyboards. I'm not sure if the upgrade to iOS 14 re-added that Emoji keyboard (I can't remember if I had previously removed it), or if something else happened during an upgrade, but the custom press fix is working again for ctrl + space. 🎉 Sharing here in case this saves someone else some time.

**Comment by treyharris** [comment]
> I was running into the issue with the Emoji keyboard popping up again for ctrl + space, even with the custom press fix in place. What eventually got it working again was removing the Emoji keyboard from Settings -> General -> Keyboard -> Keyboards. I'm not sure if the upgrade to iOS 14 re-added that Emoji keyboard (I can't remember if I had previously removed it), or if something else happened during an upgrade, but the custom press fix is working again for ctrl + space. 🎉 Sharing here in case this saves someone else some time.

Yes—it’s always been the case that if you want ⌃␣  passthrough you have to disable the Emoji keyboard plus any international keyboards that can’t be bound to Caps Lock. This probably needs to be more visibly documented. @pcho or @carloscabanero ?

**Comment by carloscabanero** [comment]
This was finally added to Q&A https://github.com/blinksh/blink/discussions/1923
