### ISSUE TITLE
Unable to connect over ssh using ssh keys

### ISSUE THREAD

**Issue by woutderooms** [blinksh/blink#1043]
**Device:** iPad mini 5 
**iOS version:** 13.5.1
**Blink version:** 13.5.1.237
**Problem:** Impossible to connect using ssh key.

I tried a multiple of ways to create an ssh key. first through the settings menu, next through the command line and importing it from clipboard. I always update my server (a Digital Ocean droplet, which works perfectly with my mac) but I can't seem to get it working.

I tried both the `ssh` and `ssh2` command.
I tried setting up the host in the settings and assigning the key and I tried manually providing the hostname (and also ip) through the cli. All which result in a failure to connect.

At first I just got silent errors (just getting the blink prompt again) but I learned you can add -v and -vvvvv to get more verbose logging going.

when running `ssh -v test` (where test is my configured host with the ssh key assigned and root set as user) I get the following log:

```
socket_callback_connected: Socket connection callback: 1 (0)
ssh_key_cmp: key types don't match!
ssh_known_hosts_read_entries: Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
blink: setting socket keepalive: 1
ssh_key_cmp: key types don't match!
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
blink: using auth methods attempt: 1 of 5
blink: import key test
ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey
```

I've bought the app more than a month ago but I cannot get it to work. When using normal username and password prompt (for example when trying to remote log in to my mac) it works like a charm.

**Comment by beacoding** [comment]
following this as I’m experiencing the exact same thing

**Comment by shvechikov** [comment]
I'm having the same...

**Comment by thoschworks** [comment]
The same issue here.

**Comment by javierdemartin** [comment]
We've been rewriting for the past months some core aspects of Blink like SSH that should fix some of those issues in the coming releases.

**Comment by MichaelSaucier** [comment]
> We've been rewriting for the past months some core aspects of Blink like SSH that should fix some of those issues in the coming releases.

This is still an issue after 2+ years?

**Comment by carloscabanero** [comment]
No, this was completed and we just did not update the issue.

**Comment by MichaelSaucier** [comment]
Oddly I am still unable to connect, when Termius connects instantly with the same information.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by carloscabanero** [comment]
Open a support ticket on Discussions and include your verbose output and instructions on how you are trying to connect. Are you reusing the same key on Blink and on Termius? Are you using the same user name? If the key is different, have you copied it to the server first?

This issue was referring to "silent error messages" that were affecting key log in issues and some errors with some key types. We fixed both long time ago (moved to OpenSSH for keys, we now have a fully re-done ssh setup, etc...)

**Comment by MichaelSaucier** [comment]
Sorry, my bad. I tried to issue the same command as in Termius, but Blink has handy Hosts which encapsulate the entire thing. When I added a host rather than type the whole ssh command it worked perfectly.

Now back to loving blink, thanks!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by carloscabanero** [comment]
No worries at all, glad you figured it out! And thanks for the heads up on the issue. We need a full repo cleanup
