### ISSUE TITLE
App does not work when using the iPad in an external screen

### ISSUE THREAD

**Issue by muammar** [blinksh/blink#1075]
I have the paid version, and when I am working on an external monitor, I can connect to remote ssh servers. However, if I change and do something on another window and come back to blink, I cannot interact anymore with my session -- keyboard does not register any key.

**Comment by javierdemartin** [comment]
When you connect your iPad to an external monitor, either via a HDMI adapter or AirPlay, and open Blink two terminals should open instead of mirroring the iPad's screen.

To switch between screens (iPad & monitor/TV) press `⌘ + O`. You can also move the current terminal to another screen using `⌘ + Shift + O`.

Feel free to experiment and test it out and reach back if you need further assistance. If you hold the `⌘` key you'll be prompted with all the available shortcuts.

We've released a new set of [docs](https://blink.sh/docs/) for users to fully understand Blink Shell. Working with multiple screens is not yet documented but we'll add it.

**Comment by muammar** [comment]
> When you connect your iPad to an external monitor, either via a HDMI adapter or AirPlay, and open Blink two terminals should open instead of mirroring the iPad's screen.
> 
> To switch between screens (iPad & monitor/TV) press `⌘ + O`. You can also move the current terminal to another screen using `⌘ + Shift + O`.
> 
> Feel free to experiment and test it out and reach back if you need further assistance. If you hold the `⌘` key you'll be prompted with all the available shortcuts.
> 
> We've released a new set of [docs](https://blink.sh/docs/) for users to fully understand Blink Shell. Working with multiple screens is not yet documented but we'll add it.


Thanks for the explanation. I will test it out and update you later.

**Comment by muammar** [comment]
I confirm this worked. Pressing `⌘ + O` activated the keyboard on the monitor.  I will proceed to close this report. Thanks for this amazing tool :)
