### ISSUE TITLE
Did not find remote IP address

### ISSUE THREAD

**Issue by withshe** [blinksh/blink#1151]
When I restore backup on my new iPhone, blink can load config from iCloud, but mosh to my server, always say “ Did not find remote IP address”, and my iPad is work normally.

Please tell me how to fix this, Thanks!

**Comment by carloscabanero** [comment]
When you get your information back from iCloud, that does not include the key (although it includes the key name). This is because we do not synchronize keys for security, but we synchronize key names so that on your devices you can use a key named in the same way.

In any case, you need to add a new key to your server for your new device.
