### ISSUE TITLE
bling-show-file freezes ssh connection

### ISSUE THREAD

**Issue by kuochang** [blinksh/blink#1170]
### Checklist

- [X] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink Version 13.5.9
iOS Version 14.2

### Describe the bug

I used the blink-show-file.sh file provided in the twitter post attempting to open a image file on a remote server (https://gist.github.com/yury/1e1db54f5a35a804604b1ae1b2657b51).
When executed, the ssh connection froze and a white dash appears in the center of the screen.
I think it’s the issue of #663, but it happened again...

**Comment by jmeosbn** [comment]
Hi there, I just saw this and gave it a try.

However, the image is not scaled and so large images seem not to be shown (on an iPhone anyway). In fact, if you zoom _all_ the way out (so text cannot be read) the image appears.

Any chance this could be auto-fitting to the availability space? 

This would allow me to avoid a round trip to another app and back when required.

Many thanks!

**Comment by jmeosbn** [comment]
Hi there, I'm sorry to be a pain since I appreciate the latest build that addresses this.

However I have not long found that passing `width=375px\;height=375px` to the script rendered images at full width and apparently (despite the numbers) full quality / resolution.

Note: curiously using numbers "near" to the above "snaps" to the width, so it seems some logic is present for this (ie. it's impossible to get a narrow margin down the side - a good thing imo), as well as the options, in the hterm functionality?

I was just implementing this into a workflow where it's very advantageous to have full width display of the original image (I was previously swapping to the - now defunct - Transmit app) when the new build became available; unfortunately this seems to override these options and only uses about 3/4 of the screen width.

Would it be possible for blink to just "fit" the image to screen if it would otherwise be larger (no change of image data, as the above appears to do) and otherwise respect the options passed? Or some options to pick either behaviour?

Many thanks!

P.S. the extra line shown after the image is not particular to this build, but caused by the terminal sometimes requiring `<enter> / ^C` to return to the prompt.

![image](https://user-images.githubusercontent.com/530912/103291449-a8016680-49e3-11eb-89a1-d6d9566c9617.png)

![image](https://user-images.githubusercontent.com/530912/103291469-b485bf00-49e3-11eb-9cf3-df0ded8407dc.png)

**Comment by jmeosbn** [comment]
One thought regarding some options for this functionality - it would make a great feature more discoverable to the user* and provide a place to link to the script.

_* I'd previously found the similar script in the hterm source - because I'm a terminal nerd - and was (obv) unable to get it to work. Apart from there and this issue (and now, TestFlight), I'd not otherwise know about this awesomesauce_

**Comment by jmeosbn** [comment]
A note to the above. I've noticed the images shown are "softer" than elsewhere, so it appears there is some image resizing / loss of resolution happening (still on build 257).

I don't think it's possible for the blink.app to do any bandwidth saving - it'd require an image resize *before* the client-side script I think - so as the full image is being sent anyway, it'd be great if that could be displayed as is?

Here is a zoomed in screenshot comparison, first the blink app:

![image](https://user-images.githubusercontent.com/530912/103486026-ad4f1e80-4df2-11eb-8c38-447c2f2ca3ca.png)

Here, the original (2400x2400px) image is shown, fit to the 1170px wide image above.

![image](https://user-images.githubusercontent.com/530912/103486056-e12a4400-4df2-11eb-89b3-4003ddcaa2bb.png)

**Comment by jmeosbn** [comment]
@yury should I have posted this in a new issue? I didn't mean to hijack the thread! 🤦🏻‍♂️

**Comment by carloscabanero** [comment]
We have users doing this regularly, so I'm assuming this is not an issue anymore. Please reopen if necessary.
