### ISSUE TITLE
Support for Eternal Terminal

### ISSUE THREAD

**Issue by wizdude** [blinksh/blink#1186]
Would it be possible to add support for Eternal Terminal?

https://eternalterminal.dev/

it’s a newer alternative to Mosh and fixes a few shortcomings that Mosh has. 

Loving your work :-)

**Comment by nanzhong** [comment]
https://github.com/blinksh/blink/issues/597 Seems to have some more historical context around this. It seems that resource constraints are the main reason this hasn't been looked into yet; from that issue, @yury is planning on taking another after Blink 14 is complete.

**Comment by carloscabanero** [comment]
Opening a quick conversation as I am not sure I understand what ET brings to the table. If we were able to give persistent tunnels and agent forwarding, etc... with what we have, what does ET do differently?

I am a bit worried with the internals for ET, not sure I understand them. The idea that a tunnel may be holding information on the other side, those buffers, etc... make me a bit uneasy. Mosh is focused on just the terminal side, and I think they made the right choice there. I think everything else can be solved at the ssh layer.

**Comment by nanzhong** [comment]
I'm also not super familiar with ET and am a mosh user, but from my understanding the difference is that mosh is udp based and works by synchronizing the display state of the terminal, whereas ET works by providing a buffered/backed reader/writer so that it can provide a "resumable" tcp connection.

Practically I feel like the main difference is that with mosh there are always going to be edge cases around osc escape sequences and other things that depend on history that could be lost in the state synchronization it uses, whereas ET would not have those limitations. This is also a downside to ET, since mosh would work much better in situations where the client has a poor connection of when there is a lot of display changes.

I don't have a strong opinion on ET. Seems like if it's easy to cross-compile and include, it provides and additional option to Blink users. It's also apache licensed so there shouldn't be any license concerns here.

**Comment by arkku** [comment]
Based (only) on the ET website, one potentially interesting feature is the tmux control centre support. If I understand correctly, it would allow handling the split screen, tabs and tmux keybinds locally. This would potentially allow using native touch controls and keybinds configurable in blink to split and resize tmux panes. Which would be neat. Otherwise I’m a bit sceptical of ET for the time being.

**Comment by bensleveritt** [comment]
I'd like to add that I use both Mosh and ET daily, depending on context, and would appreciate the option. As it is I have to SSH to a local box, then ET to the remote as a work around, but ideally I'd just use ET directly. 

I get the impression it's possible to build Blink with additional binaries, and run on one device. Is this an option for testing with?

**Comment by aimerib** [comment]
Wanted to add my support for this feature as well. For me, it is mostly losing scroll history with mosh that makes it basically unusable for me, so I end up having to go back to regular ssh. Will have to try @bensleveritt idea of a jumpbox.

**Comment by yury** [comment]
@aimerib mosh is usually used with `tmux` and `screen`. I personally recommend `tmux`.

**Comment by aimerib** [comment]
@yury I am actually setting up tmux for this server right now. I usually use ZelliJ (a more modern alternative to tmux) but this server is the only one I use with my ipad as well, and the combination of mosh + zellij is pretty broken (potentially due to ZelliJ being so new? not the point though) and I found ET to work really well.

I figured I’d leave my vote of support for ET, but also be practical about it and get tmux setup anyway.

Sidebar, the main reason why I use ZelliJ over tmux is the simplicity to get up and running. Without any configs, out of the box ZelliJ is perfect (for me, others might hate it), whereas I’m hunting down tmux config files because I don’t really want to spend hours learning how to configure it manually. This is always the balance though, isn’t it? Some things work everywhere but maybe not how everyone wants, and other things are much more friendlier to use, but more restricted in availability.

At any rate, thank you for the suggestion, and it is what I will be doing for now

**Comment by yury** [comment]
@aimerib I will look at ZelliJ. If you can, please record video of broken mosh+zellij.

I suspect it may be broken as fish. It could be fixed with mosh prediction overwrite toggle in host settings. But it is my initial idea. Will investigate.

**Comment by wizdude** [comment]
> whereas I’m hunting down tmux config files because I don’t really want to spend hours learning how to configure it manually.

i personally don't like heavily customised environments, because when i go to use a host that's not mine, i don't have my special configuration. i always use tmux in its stock configuration. about the only thing i ever (sometimes) configure is support for the mouse.

if you need a handy reference, check out this site: 
https://tmuxcheatsheet.com/

**Comment by aimerib** [comment]
@wizdude That makes a lot of sense, and is a sentiment I used to share in a previous career as an SRE, but these days I only ever use the same three boxes, and have created pretty ambitious golden images and ansible playbooks to bring any one of those boxes back to “perfect” working order.
The very few instances when I am remoting into a machine that doesn’t have my configs is usually for a really quick test, and I won’t really be needing any other special tools, at least not for long.

I hope my previous comment didn’t come across as a jab at tmux though. I really appreciate a tool that can be pretty good barebones (or at least good enough) but infinitely configurable. The whole different strokes for different folks, but all in one tool

**Comment by aimerib** [comment]
@yury just as an update, changing the mosh setting in the host settings seems to have fixed this for me! This is fantastic!

**Comment by wizdude** [comment]
> I hope my previous comment didn’t come across as a jab at tmux though.

not at all. i'd never heard of ZelliJ before. like you said, different tools for different people.

i work as a support engineer, so i need to ensure most stuff i do is consistent, repeatable and available on most stock OS's, so tmux is the winner for me. prior to that i always used gnu screen and stuck with it for years, until i found out about tmux and saw how multiple terminals could control the same session simultaneously. that blew my mind and i wondered why i hadn't changed much earlier.

i'm currently using Blink with tmux and it works quite well, but eternal terminal steps the game up a bit, especially with some of it's tmux support. would be nice to see it supported in Blink.

**Comment by wizdude** [comment]
> changing the mosh setting in the host settings seems to have fixed this for me! This is fantastic!

just out of curiosity - what did you change?

**Comment by aimerib** [comment]
<img width="1180" alt="Screenshot 2022-12-27 at 8 30 42 AM png" src="https://user-images.githubusercontent.com/26142232/209674027-7f705be3-d5eb-435b-8f36-ff1dcffb5722.png">

This is in settings, hosts, select your host, mosh, predictive settings. Not sure if it does anything for tmux, but in zellij the screen doesn’t look broken, and zellij can properly handle history scroll, scrollback, and thats pretty much all I was missing.

**Comment by carloscabanero** [comment]
Closing here in favor of #597
