### ISSUE TITLE
I have issue connecting to mosh server

### ISSUE THREAD

**Issue by devch96** [blinksh/blink#1194]
Hi. I just started using mosh server and i successfully established connection between my device(ipad) to mosh server until WIFI condition. But when i tried to access to the server with same device but using cellular data, it doesn't work and shows this error line,[ Socket error: Socket is not connected
Did not find remote IP address. Could you please assist me to fix this issue? ]
And also, how do i restore my resolution settings into default?

**Comment by marchenk0** [comment]
@devch96 this is look like it was happened because your mosh-server had different IP addresses:
1. Internal IP in your WiFi
2. External IP in cellular network
If you used your laptop or pc as a mosh server then they will have different IPs depending of mosh client location: internal WiFi network or external network.
