### ISSUE TITLE
SSH key lost

### ISSUE THREAD

**Issue by jakub-stastny** [blinksh/blink#1253]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

- iOS 15 first public beta (current beta version).
- Blink 13.5.12.262

### Describe the bug

I had 2 SSH keys in Blink, the default `id_rsa` one and another one called `AWS`, which I created in Blink a few months ago.

I use mosh to connect. The terminal broke (which sometimes happens), I try to reconnect and nothing. I go `ssh -vv` and see that my AWS key is missing. I go to settings/keys and it really has gone.

May or may not be related to #798.

**Comment by jakub-stastny** [comment]
Is there any way of recovering the key?

- Are the keys in iOS backup?
- Is there a better way of recovering that recovering from an iOS backup? (Which doesn't allow to recover one app only, so it's a huge hassle.)

**Comment by carloscabanero** [comment]
Thanks for the report @jakub-stastny, it seems to be an issue affecting some of us on iOS15. It is actually the whole configuration that may not be accessible. What we have discovered so far is that restarting the device - sometimes multiple times -, can bring everything up again. 

At this point, and due to the unstable nature of some of the iOS15 issues we are seeing, we are not actively working on it but we are keeping an eye on things.

Let us know if restarting actually worked for you as well.

PS: For security reasons, keys are not kept on any backup. If you wanna continue on iOS15, after the key comes up again, I would suggest to copy it to your sandbox. Then you can do `ssh -i key_name` and access it from file.

**Comment by treyharris** [comment]
> PS: For security reasons, keys are not kept on any backup. If you wanna continue on iOS15, after the key comes up again, **I would suggest to copy it to your sandbox.** Then you can do `ssh -i key_name` and access it from file.

What are the steps to copy it to your sandbox? And then is `ssh -i key_name` sufficient to restore it? Is this documented somewhere?

**Comment by jakub-stastny** [comment]
@carloscabanero tried the restarts, but it didn't help. In my case it was only this key, the rest of the configuration is intact. Well, never mind, I set up a new VPS and saved the key this time.

**Comment by sollymay** [comment]
+1 to losing all my configuration on iPadOS 15. It’s so random, cause it can happen at any point in time and then you have to redo all your settings.

**Comment by pcho** [comment]
> +1 to losing all my configuration on iPadOS 15. It’s so random, cause it can happen at any point in time and then you have to redo all your settings.

Just seconds ago I had the same issue, but going to Settings > General > Shut Down works for me each time. The thing is that all the settings are still there, they will disappear only when you recreate them. It's worth a try before doing that again. :-)

**Comment by jakub-stastny** [comment]
It just happened again, the scenario was exactly the same: it lost 1 key (the non-default one, which I was currently using, just as the last time), no other configuration was lost.

It's really annoying.

**Comment by ajc** [comment]
I've seen this too. Whenever it happens, force-quitting Blink is enough to get my settings back - I haven't had to restart the whole device.

**Comment by tuna-f1sh** [comment]
Had this happen > 5 times on iPadOS 15. Generally the settings disappear and come back on force-quit. I have to reload my private key however since I name it as the default (id_rsa).

**Comment by seriousm4x** [comment]
I also lost all my settings and private keys. When restarting the app, the settings come back sometimes but the keys never. Blink just created the default id_rsa again. Seems like they are lost forever.

**Comment by seriousm4x** [comment]
I just want to briefly appeal again how important a fix is for the issue. Next Tuesday is keynote and Apple will release for iOS 15. All people who update and use Blink will lose their SSH keys.

**Comment by carloscabanero** [comment]
We don't think the issue is on our side. Nonetheless, we have a workaround so that keys and other information is not overwritten, and we added more additional debugging through alerts as it seems the issue is during reads/writes.

We will push tomorrow. If I recall from other years, the release doesn't happen immediately. They may cut gold, but still give one or two more weeks.

**Comment by carloscabanero** [comment]
Just a heads up, this was fixed and pushed on AppStore.

It will come to TF this week as well.
