### ISSUE TITLE
Can we install packages in the Blink shell?

### ISSUE THREAD

**Issue by julkhami** [blinksh/blink#1284]
Is it possible to download and compile packages with the command make or a package manager such as apt? If not, why?

Thanks very much.

**Comment by arkku** [comment]
Apple does not accepts apps with such capabilities, since it would enable circumventing their App Store (e.g., potentially one could get the platform app approved and then sell nested apps outside of the App Store for running inside). So at least the App Store version of Blink would need to ship with everything pre-installed, and I believe it can’t include stuff like compilers, either… Not sure how strict they are nowadays about simple scripting, i.e., would it be possible to package something like bash or zsh since they can run shell scripts, or even vim/nvim.

**Comment by arkku** [comment]
Actually. my above comment may turn out to be slightly incorrect: despite threatening to remove it from the App Store, Apple has accepted [a-Shell](https://github.com/holzschu/a-shell), which contains compilers, and you can thus install software on it locally by compiling from source. Apparently the way they have done it is by compiling C to webassembly, not native code.

**Comment by carloscabanero** [comment]
There are many limitations with the sandbox that do not make this possible, or that make it very cumbersome. a-Shell is trying some things that are working ok, and we are keeping an eye.

Our focus on Blink though is on remote. Because that is where things are headed.

**Comment by rbreaves** [comment]
Ooof looks like iSH is ahead of you and everyone else in this regard. They do have a package manager.. it's apk, Alpine. Some syscalls are not implemented though so not all apps work, it is very impressive though.
