### ISSUE TITLE
Keygen with Passphrase

### ISSUE THREAD

**Issue by lrentz** [blinksh/blink#1312]
When generating a key I do not get an option to add passphrase via command line or gui. Any ideas?

**Comment by carloscabanero** [comment]
Since Blink 14, we only support keys stored inside Blink, as they are more convenient for upcoming features. Blink stores keys already encrypted by the Secure Enclave in your device, so we decided to move on from additional encryption from passphrase. You can also protect the whole app from unlocking if necessary.

So that’s why there are no passphrases, we do not think they are necessary anymore.

**Comment by nickhammond** [comment]
I really like the simplicity of key creation in Blink as you can create one and then copy it over to Digital Ocean for instance to spin up a new machine, just putting in a vote to keep them.

If passphrases are no longer supported though it’d be nice to remove the paragraph that talks about them in the documentation https://docs.blink.sh/basics/ssh-keys.
