### ISSUE TITLE
Blink using large amount of iPad storage

### ISSUE THREAD

**Issue by andrewjj20** [blinksh/blink#1338]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

- iOS 15.2
- Blink 14.0.3.370

### Describe the bug

Blink is using a significant amount of storage, Gigabytes that cannot be located or corrected. Looking at the size. It could be related to recent file transfers using the Files.App feature that failed.

Clean up or allow the clean up of this space.

**Comment by jaclu** [comment]
In Blink you can use ls -la  to see sizes for dot files
if I do ls -la .blink I have a fairly large file fileprovider.log a couple of hundred KB in size. Since there is no local more or less, I just did
scp .blink/fileprovider.log hostname:
to get it over to one of my nix boxes and there I could examine it.
In my case it was tons of sftp errors stemming from when I was experimenting with using Blink as a virtual file system.
Not the sizes you have seen, but digging around with ls -la might show you what is eating all the space.

**Comment by carloscabanero** [comment]
Yep, great catch. Unfortunately the File Provider does not seem to unload big files until necessary, which is usually too late. Will add a way to clean up, or access to the FileProviderStorage so you can "rm -rf" there.

**Comment by carloscabanero** [comment]
You should already be able to do `rm -rf ../File\ Provider\ Storage` From Blink’s root. That will kill everything. Please close the file app after doing that, so the cache is also reset.
