### ISSUE TITLE
Character width when bold is enabled

### ISSUE THREAD

**Issue by g6ai** [blinksh/blink#1339]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink version: v14.0.3.370
iOS version: 15.1

### Describe the bug

At the bottom right corner, the numbers are overlapped by powerline characters. In Blink app settings > Appearance > Enable Bold, if I set it to Auto or On, the problem is there. When I set it to Off, problem is gone.

![IMG_406A0A975411-1](https://user-images.githubusercontent.com/7374104/146448426-8d5e356d-42f3-4aac-99a0-fa3e678ada07.jpeg)

**Comment by carloscabanero** [comment]
This may happen if the font does not provide hints for bold rendering or if the powerline font is not properly patched.  When a font does not provide bold variants, enabling "Bold as bright" is recommended. Otherwise Blink will let the renderer try to hint Bold and that is know to cause issues (it is very common in the browser too). 

We now provide a new repository with properly patched fonts at GitHub.com/blinksh/fonts. Closing here.
