### ISSUE TITLE
Mosh startup command auto-finishes the session

### ISSUE THREAD

**Issue by marchank0** [blinksh/blink#1377]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
iPad
- iPadOS 15.2.1
- BlinkShell 14.0.6

iPhone
- iOS 15.2.1
- BlinkShell 14.0.6

Mac
- mosh 1.3.2 [build mosh-1.3.2-102-g378dfa6-dirty]

### Describe the bug

I have the same result for iPhone and iPad
I tried different variants for startup command like ls, pwd, /usr/local/bin/tmux, /urs/local/bin/neofetch, run them with cli or host config and in case of neofetch I can even see for a half of a second like Blink prints mac's information, but right after that session finished automatically.

I should see the startup command execution result and be able to work with created mosh session without auto-closing.

Run mosh with verbose parameter
![Blink mosh finished session after start command](https://user-images.githubusercontent.com/1183579/151796204-72ccd09c-2393-497c-b4dc-dfb1611b7844.png)

https://user-images.githubusercontent.com/1183579/151816417-12369c78-3cd0-4493-8dd7-b46b7643356e.MP4

Host configuration
![Blinkshell settings](https://user-images.githubusercontent.com/1183579/151796384-7933282d-9c61-44bb-92d9-c10584520c41.jpg)

I installed Termius for comparison to see maybe the error is on my side.
Termius is running mosh with the same startup command
![Termius successful result](https://user-images.githubusercontent.com/1183579/151796529-3150177f-8154-4f40-a73f-22fbb58f8941.png)

Termius host config
![Termius mosh connection details](https://user-images.githubusercontent.com/1183579/151796586-983d5d71-c85b-40a4-a40c-decdca047285.png)

**Comment by Gex2501** [comment]
I have the exact same issue. And it’s been an issue from the beginning of Blink. This has never worked.

**Comment by carloscabanero** [comment]
This works for me with tmux (so not true that this has never worked from the beginning). Normally this issue is due to problems locating the command, but that is not the case with neofetch. It looks like the shell is not holding right after executing the command, and hence mosh exits.

EDIT: Take into account that commands like `ls`, `pwd`, etc... will actually work but because mosh cleans up the terminal to start showing its own "Terminal rendering", they will execute and take you back to the shell. That happens with regular mosh. For those cases you should use ssh.

I will spin up a machine to figure out what may be going on. I do need more time because we are a bit swamped making sure everything goes smoothly with Blink 15, but will get to this right after.

https://user-images.githubusercontent.com/536729/153905659-93b53370-169e-468e-9c60-6dcd2f863334.MP4

**Comment by Gex2501** [comment]
> This works for me with tmux (so not true that this has never worked from the beginning). Normally this issue is due to problems locating the command, but that is not the case with neofetch. It looks like the shell is not holding right after executing the command, and hence mosh exits.
> 
> EDIT: Take into account that commands like `ls`, `pwd`, etc... will actually work but because mosh cleans up the terminal to start showing its own "Terminal rendering", they will execute and take you back to the shell. That happens with regular mosh. For those cases you should use ssh.
> 
> I will spin up a machine to figure out what may be going on. I do need more time because we are a bit swamped making sure everything goes smoothly with Blink 15, but will get to this right after.
> 
>  RPReplay_Final1644856366.MP4

Okay! Okay! You were right! I’m an idiot… once I put the full path to tmux in the blink host config it worked perfectly. Also, to maybe help out someone else, I’m using zsh with oh-my-zsh, which looks like it has an alias to the tmux command. Might be related to my issue.  ¯\_(ツ)_/¯
