### ISSUE TITLE
Blink 15 did not import all keys from Blink 14

### ISSUE THREAD

**Issue by giddyhup** [blinksh/blink#1388]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink 15.0.1.516 and 14.0.9.440 under iPad OS 15.3

### Describe the bug

Of the three keys stored in Blink 14 only one got imported.

**Comment by carloscabanero** [comment]
Are the rest of the keys Secure Enclave keys?

**Comment by giddyhup** [comment]
> Are the rest of the keys Secure Enclave keys?

No.

**Comment by minivi** [comment]
> Are the rest of the keys Secure Enclave keys?

In my case, I only have 1 key and it's a Secure Enclave key. Can it be migrated from v14 to v15?

**Comment by carloscabanero** [comment]
Secure Enclave keys cannot be migrated because they cannot be read by anyone. That is their advantage, that turns into a disadvantage in this case as we cannot export them.

@giddyhup Im unsure at what may be going on. Does the app crash or they are just not copied? Is there an error at any point? Did Blink generate these keys? What type of keys are them? We are waiting for Apple to approve a new version that may work with the other keys, but it is for a case when keys do not have comments. 

My suggestion is, if you don't have a lot of keys, to just migrate them manually by importing them from the clipboard.

**Comment by giddyhup** [comment]
@carloscabanero it could be that the app crashed since after the import step end up with the home screen. I tried an import via the clipboard and can see that entries were created but I am not sure there was an actual import. When I tried logging in using the newly imported key I still get asked for the password. I ended up ssh-copy'ing the default key, the one that was properly imported.

**Comment by minivi** [comment]
@carloscabanero Thank you for the response. 

So, to recap SE private key is tied to specific app (v14) and cannot be used by/migrated to other app (v15) even in the same device.

**Comment by carloscabanero** [comment]
@giddyhup Apologies for the inconvenience. We have now been waiting more than 24h for Apple to approve our new version with those fixes.

@minivi That is correct. SE keys are tied to a specific app and device, and only that app can perform signature operations with it, not even read it.

**Comment by carloscabanero** [comment]
Ok, release finally made it through. Closing here. Feel free to open a new one if any other issues show up.
