### ISSUE TITLE
Support `mosh --experimental-remote-ip=proxy`

### ISSUE THREAD

**Issue by fingolfin** [blinksh/blink#1397]
In PR #1157, support for `mosh --experimental-remote-ip={remote|local}` was added.

In the meantime, `mosh` gained a third value for this: `proxy`, and this is even the default nowadays. It would be nice if this was supported by Blink Shell.

**Comment by carloscabanero** [comment]
Sorry for the delay jumping on this. "Proxy" should be equivalent to our default way, which uses our SSH to resolve the API. Their way is calling ProxyCommand as a way to read it back, so there should be no differences. I don't want to call ours proxy though. And we are fixing "local" as per #1803.

Hope this makes sense and let me know if you need the specific ProxyCommand to be feeding back for any reason. Otherwise I will close the issue.
