### ISSUE TITLE
Using ProxyJump results in strange behavior

### ISSUE THREAD

**Issue by Son-Typ** [blinksh/blink#1450]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink 15.0.7.536 on iPadOS 15.4.1

### Describe the bug

When using the ProxyJump setting to connect to a host, some bugs occur that do not happen without that setting. Entered commands are echoed back before they are executed (see attached screenshot). Auto complete using tab does not work at all. Control+c disconnects from the host instead of only sending a SIGINT to the running program. Maybe there are other bugs related to ProxyJump I have not encountered myself.

I can reproduce the bugs on my machine simply by using a jump host. Sometimes, removing and re-adding a host fixes the problems at least for a short time before they start happening again. This does not happen on any other SSH client (iPad or other systems) using the same hosts.

<img width="334" alt="proxyjump-bug" src="https://user-images.githubusercontent.com/44496385/161431501-bd948573-9e59-4855-aa53-975c649d7263.png">

**Comment by domcylai** [comment]
Hi,

I would like to echo that I have the same issue under my iPad Air 5, with Blinkshell version 15.0.7.536 (installed via App Store).

Specically, I have 2 hosts, namely:
    *  A as the bastion host running RHEL9, and
    * B as internal host running Ubuntu 22.04, but reachable via host A

I have set up the ProxyJump so that I could SSH to B via A (all through key-based authentication).

On the first run, it looks ok under host B.  I could see that there is a new sshd running under A (which is expected).  But after I issue "exit" under host B, when I log on B again, the described problem (as Son-Typ described) appears.  Typing "sudo ..." and it will end up password echoing on the screen, doing "less ..." and it does not really take any commands.

I also note that after I have issued "exit" under host B, the "new" sshd under host A (that was forked when I logged on host B) does not go away.  It still stays running under host A.  But one interesting thing is:  if I manually kill this sshd process under A, then when i log on host B again, everything comes normal!  Of course, if I choose exit under host B and does not kill the dangling sshd under A, the same issue comes again until I manage to kill the sshd manually.

I note that when I perform the same ProxyJump (actually, ProxyCommand) under Windows client to A --> B, when I issue "exit" under host B, the sshd of host A should go away.

I believe that the author should fix the app so that upon the logout/exit of host B, the app should also make sure that the connection to host A should also be ended...!

P.S. : This is really a major issue, that prohibits me from doing annual subscription for this app...

**Comment by domcylai** [comment]
Seems that I spoke too soon.  While at the first trial by killing the sshd on host A that seems to work, it does not work anymore on 2nd try.  But one interesting thing is that when I exit all ssh sessions and let my iPad idling for a period of time (say, 30 mins), then when I try again, things work again... well, for the first time, and it will not work anymore...  until another while later.  Really suspected that it is due to the unclean connection termination on each host exit...

**Comment by carloscabanero** [comment]
I have not been able to reproduce your case, but thanks to your detailed report, I think I was able to figure out what could be a possible cause for this issue. When we launch a ProxyCommand, we use another ios_system process in the background to trigger the stdio tunnel. Up until now we have been keeping this tunnel in the background while the process exited. That connection and tunnel are also making use of the ControlMaster flag, so if you then started a shell to the bastion for whatever reason, that same connection would be reused.

I have simplified the flow as connections that try to do too much are never a good idea. The process for the ProxyCommand is now kept open and tied to the previous connection. ControlMaster has been disabled for the bastion, but it is still kept in the main connection. I hope this improves the reliability in this scenario.

Should be out on TestFlight

**Comment by carloscabanero** [comment]
Confirmed via TF, Rishav:
> I had the exact same problem described in Issue #1450 with proxyjump echoing commands and ctrl-c disconnecting.  This testflight version seems to fix the issue.  I even tried redownloading the app store version, and the issue came back.  When I reinstalled this latest testflight release, it went away again 🎉

:)
