### ISSUE TITLE
Add “Mono” version to font gallery, or change the renderer for nerd font.

### ISSUE THREAD

**Issue by nanozuki** [blinksh/blink#1456]
I use the nerd fonts in repo: https://github.com/blinksh/fonts, but some characters not display correctly:

![B7EE0170-BF44-4D33-9719-8B0CC6615EDE](https://user-images.githubusercontent.com/4208028/162619264-478d90f7-c2e6-4a35-a502-90093bb46fbf.png)

Because the characters should be force render to monospace, or should use “Mono” Version for Nerd font. (For example, “JetBransMono Nerd Font Mono”)

It would be nice if you can provider that font in font gallery,

Or provide a method to add font by font files.

Termius do this almost right, but have some glitch (And I like blink’s way more):

![D0F956E5-D5AE-48FB-8321-3A8CEBDE9B6E](https://user-images.githubusercontent.com/4208028/162619402-18f445c3-e4aa-4f64-bff1-d2e3bf8c7485.png)

**Comment by carloscabanero** [comment]
Hi @nanozuki, we have provided ways to add your own fonts and font-files since the beginning (way before Termius did). You can read how here: https://docs.blink.sh/advanced/creating-fonts-and-themes#create-a-font. You also can take one of the fonts in the gallery as well. Our default Pragmata font should also ship with this.

If you have any issues, we appreciate patches here.

**Comment by carloscabanero** [comment]
We now provide a new themes repository with further instructions to patch Nerd Fonts. Closing here.
