### ISSUE TITLE
Wake-On-LAN auto-completion from Host configuration

### ISSUE THREAD

**Issue by AlexHunterCodes** [blinksh/blink#1552]
We can currently auto-complete `ssh` and `mosh` commands using the alias names of Hosts in the configuration, and Blink fills in the relevant command line arguments for us.

It would be great if we could do the same for the `wol` command from #951 to send wake-on-lan magic packets using a MAC address, IP, and port pulled from a new "Wake on LAN" category in the per-host configuration.

Then, instead of relying on text expansion to type out `wol -q -b 16.32.64.128 -p 10007 01:23:45:67:89:AB` (for example) I could just type `wol my-host`

**Comment by sofomryu** [comment]
Hi I am having trouble to use wol command in blink. I typed wol -q -b (my broadcast ip) -p (60000) (my MAC address), then it doesn't show any response. Instead, typing wol (MAC address)  shows the sentence 'Packet sent ~~'. In either case, my macbook doesn't wake up from sleep mode. Any suggestion?

**Comment by AlexHunterCodes** [comment]
@sofomryu This is a feature request, and your comment is an unrelated support query. You should put it in its own issue instead of here.

**Comment by carloscabanero** [comment]
We will add a setting in our Hosts for Wake-on-lan with the MAC address and port.
This could also be a shortcut / widget.

**Comment by carloscabanero** [comment]
Hi! So just a heads up. We have decided to add this as part of a more generic use case for integrations that we are planning, instead of building a specific UI that you need to run manually all the time.

But until we get there, our recommendation is to create a Snip (https://docs.blink.sh/basics/snips), which can work kinda like an alias for your full command. Running the Snip is super easy and more immediate than going through menus.

We will merge this use case somewhere else, but closing here.
