### ISSUE TITLE
Custom themes: no changes after import

### ISSUE THREAD

**Issue by andrius** [blinksh/blink#167]
I have copied URL for *.js for some theme from github and pasted it to the blink;
Named theme were imported successfully;
However, nothing changes with UI and new theme just inherited colours from previously selected build-in theme.
Did it few times with same result.

Not sure is that bug or I did something wrong (i.e. URL), but blink did not reported about any issue and imported theme properly

**Comment by andrius** [comment]
Update.

I did it wrong. I had to specify url for raw file, i.e.
https://github.com/blinksh/themes/raw/master/themes/Terminal%20Basic.js

However:

1. Blink importing incorrect url's
2. It's not possible to delete imported themes or overwrite them

**Comment by carloscabanero** [comment]
Awesome, glad to know you made it work.
1. The problem is that themes are currently JS code. It is then difficult to validate how well formed it is. It would probably make sense to change the format to a JSON that is easier to build and validate, and to have future terminal level plugins only with JS. Hopefully having a big library of themes would alleviate the situation at the moment. 

2. To delete themes, just swipe left. Let me know if you tried that but didn't work for you :)

Thanks a lot for your help Andrius!

**Comment by andrius** [comment]
Delete worked. Then good to have rename there too! 
Make blink page with features/help/screencasts :) 
I (and many people) like this minimalistic design, full screen... But some extra help references is good to have!

**Comment by carloscabanero** [comment]
Agreed. Very needed, working on that ;)
