### ISSUE TITLE
paywall makes me want to die

### ISSUE THREAD

**Issue by sneak** [blinksh/blink#1683]
![](https://i.imgur.com/3VfoZDm.png)

This is what it feels like when I'm shaking my device on an airplane taxiing to the runway trying to move an ebook on my server into the right shared folder so I can download it before I lose internet, whilst using your free software for free.

Ubik was not meant to be an instruction manual.

**Comment by sneak** [comment]
I am considering giving Apple $99 (several times your subscription price) just to publish a fork of this software that doesn't do this

**Comment by carloscabanero** [comment]
Closing here. Blink is not free as in beer. It costs money to develop and keep updated. 

We would take some valid criticism. Something like "I hate the paywall because...", "I would consider paying and helping you guys keep development if instead of a paywall you did...", "Maybe you should change the copy on the paywall to...".

But the reasoning behind "I will pay a big corporation $99 instead of supporting you guys to continue developing a software that I find useful" is... sound.

**Comment by sneak** [comment]
You seem to have misunderstood.  It's not "instead of supporting you".  There's no universe in which I would ever support people who abuse me as this.  The money paid to Apple is orthogonal, and is solely in service of helping others avoid being abused similarly.

Blink is *absolutely* free as in beer.  It's impossible to sell free software itself - software that is free as in freedom is also always free as in beer as a side-effect.  It's impossible to gatekeep access to software (such as on payment demand) if it's been released under a free software license.

Here, I'll show you.
