### ISSUE TITLE
Sane defaults for stage manager on iPads

### ISSUE THREAD

**Issue by yury** [blinksh/blink#1748]
We have to separate external display setting for iPads that support Stage Manager with external display and other devices.

**Comment by carloscabanero** [comment]
Adding to this, when you have stage manager, some combos like Cmd-Shift-O may not make sense anymore (and they currently misbehave).

**Comment by larme** [comment]
On a ipad without stage manager support (like ipad mini 6), the external display’s behavior is also strange. The external display have the full blink windows but I cannot change focus to external display, nor can I move a tab to the external display using shift-cmd-O.

**Comment by carloscabanero** [comment]
@larme I could not replicate this myself. Would you mind checking on config > keyboard > shortcuts and try to set it to something else and see if that helps?

**Comment by yuutayamada** [comment]
Hi @carloscabanero, I am using iPad mini 6 and could confirm that @larme’s case. It doesn’t happen until I turn off my external monitor and then turn on. I was using key combo of CMD-Shift-Control-O at the moment. I don’t usually turn off the monitor like that, but it could be similar situation when my external monitor turn off automatically due to no input long time if I leave somewhere.

**Comment by yury** [comment]
[Based on](https://gist.github.com/adamawolf/3048717?permalink_comment_id=4363196#gistcomment-4363196) we need double check device names.

**Comment by deasmi** [comment]
Stage manager support is utterly broken. 

Having just got an iPad Pro and plugged it into a screen I was looking forward to blink working nicely, it just doesn't.

Currently I have a black, not normal background color, rectangle on my ipad and a blink window on the external screen, which is full screen from an iPad perspective ( ie. no side icons ) but only using a rectangle of around 60% in the middle. 

I cannot shut any windows, manage any windows, or otherwise try and fix this as when blink is in the foreground I can't even move the mouse to the external screen. 

I'm going to reboot and see if that fixes this, otherwise I'm at reinstalling blink.
