### ISSUE TITLE
Feature Req: Add libfido2 to directly support hardware tokens for SSH auth

### ISSUE THREAD

**Issue by jac-cbi** [blinksh/blink#1763]
_snip_

> We won't support FIDO2 atm as it would require custom support per key and honestly, the user interest is just not there.

> _Originally posted by @carloscabanero in https://github.com/blinksh/blink/issues/1759#issuecomment-1527699050_

This didn't sound right to me, so I did a little digging.  I found [libfido2](https://github.com/Yubico/libfido2) which is BSD2-clause and is published by Yubico to facilitate speaking to all FIDO2 (and FIDO fwiw) devices.

I'm not sure how iOS / iPadOS might like this, but it would seem to be worth a shot for Blink...

**Comment by jac-cbi** [comment]
Doh!  Did you know ssh has built-in support for FIDO2?  I think this is all that is needed in the `ios_system` repo

```diff
diff --git a/ssh_keygen/config.h b/ssh_keygen/config.h
index bdde4922814e..8aada7d6e1e6 100644
--- a/ssh_keygen/config.h
+++ b/ssh_keygen/config.h
@@ -138,7 +138,7 @@
 #define ENABLE_SK 1

 /* Enable for built-in U2F/FIDO support */
-#undef ENABLE_SK_INTERNAL
+#define ENABLE_SK_INTERNAL 1

 /* define if fflush(NULL) does not work */
 #undef FFLUSH_NULL_BUG
```

Cc @yury

**Comment by jac-cbi** [comment]
If you prefer to stick to the GUI interface for key mgmt, you may want to keep `ENABLE_SK_INTERNAL` undefined, and set `$SSH_SK_PROVIDER` to the path to `libfido2`.  Then you could also use `libfido2` from Swift for the GUI.

**Comment by jac-cbi** [comment]
Gentle ping @carloscabanero , @yury ?

**Comment by carloscabanero** [comment]
Last time I looked, the problem was precisely the libfido2 - iPadOS compatibility. That’s why for the most part you need to use their SDK, and why even the SDK is only supported in parts for some devices, and the reason why FIDO2 is not supported on more apps.

We opted for WebAuthn as we thought the protocol was great and it will replace FIDO2 for general use. It will continue catching up and growing adoption. I also figured out a way to make it work with the agent without changing the server.

I am now waiting for WWDC to see what the next steps should be.

PS: I lost my HW key too. I do hate HW keys and I am really surprised companies didn’t substitute for SW keys that would actually be more secure. Anyone has any insights there?

**Comment by carloscabanero** [comment]
Merging with #1762
