### ISSUE TITLE
all sessions lost after 24hrs inactivity

### ISSUE THREAD

**Issue by dudalev** [blinksh/blink#179]
Hi!

Just a short question - if I leave several sessions (including one actually connected via mosh) for a longer duration (e.g. more than 24 hours), is Blink expected to keep them? That is, when Blink was inactive for a couple of hours, everything was fine, but when I haven't activated Blink for almost a day, and used other apps a lot, I found Blink completely lost its state.

Cheers,

Michael

**Comment by carloscabanero** [comment]
Hi Michael and thanks for your message! 

Usually other apps kill the connections every three minutes due to iOS limitations. Blink is able to preserve Mosh sessions for as long as the application remains open.  With SSH connections, Blink isn't different than any other app, although due to lower memory consumption, etc... I have seen those "couple hours" too. What you experienced was probably iOS killing the app, and I'm working as we talk on a way to preserve Mosh connections #59 after app restarts, so that Blink becomes indestructible.

I suggest you run all you can through Mosh as that is the most optimum case. We have been able to keep connections open for days, even after making heavy use of other apps. It is just more optimized, and iOS will also preserve it longer the more you use it.

**Comment by dudalev** [comment]
Thanks! I'm looking forward for #59 since it would be totally awesome.

**Comment by carloscabanero** [comment]
I will close here, please track #59! :)
