### ISSUE TITLE
Some Ctrl-prefixed keys combinations are not working properly

### ISSUE THREAD

**Issue by xinan** [blinksh/blink#180]
Hi! I have actually sent this through TestFlight but after that I feel that it is better to put it here. 

Basically there is some issue with the Control key on my iPad Pro, and it demonstrates different behaviors between software keyboard and hardware keyboard.

- On the software keyboard, <kbd>C-/</kbd>, <kbd>C-;</kbd>, <kbd>C--</kbd>, etc sends special characters like `Ï`, `Û` and `Í`.
- On the hardware keyboard, they just sends `/`, `;` and `-`, the <kbd>Ctrl</kbd> key seems to be ignored in this case.

This causes some problems in using Emacs. 

The software keyboard problem happens on both my iPad and my iPhone. I don't have a hardware keyboard for my iPhone, so I only tested it on the iPad with a Smart Keyboard.

**Comment by carloscabanero** [comment]
Thanks for reporting this Xinan :)

<kbd>C-/</kbd>, <kbd>C-;</kbd>, <kbd>C--</kbd> in theory, are not ascii control codes (http://academic.evergreen.edu/projects/biophysics/technotes/program/ascii_ctrl.htm), and iTerm for example in the <kbd>C-;</kbd> just returns ";". I might be all wrong and there might be an extension to this.

The debug definitely at the moment is that the sw and hw keyboard return different things. Further than that, what is the expected behaviour do you want? You can test what your computer returns with a "showkey -a", and then we can see what to do with it. Then we will be able to fix it further than this :)

Thanks!

**Comment by xinan** [comment]
On Gnome Terminal, <kbd>C-/</kbd> and <kbd>C--</kbd> both actually send <kbd>C-_</kbd>. This would be my expected behavior. <kbd>C-;</kbd> on Gnome Terminal sends <kbd>;</kbd> but I have no preference for that. 

Interesting note: On a Ubuntu tty, <kbd>C-/</kbd> actually sends <kbd>C-?</kbd>.

**Comment by cheapRoc** [comment]
I'm getting the same thing for some of my most commonly used keys, like `C-@` and `C-/`. Using an iPad Pro with Emacs if that helps and haven't tested much else yet.

**Comment by jramapuram** [comment]
+1 for this. `C-/` is pretty necessary for basic emacs usage
