### ISSUE TITLE
Keys stop working when using Universal Control

### ISSUE THREAD

**Issue by muddi900** [blinksh/blink#1805]
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
**Blink**: 16.1.10.772
**iPadOS**: 16.5.1
**macOS**: 13.4
**Keyboard**: Logitech Trackpoint Keyboard II running over Bluetooth
**Settings**:
 - Full Keyboard Access: On/OFF (Irrelevant)

### Describe the bug

When transfering to iPad running blink shell, the Spacebar, Shift and Tab keys stop working. They will work one time and then stop working.

Video Link: https://youtu.be/-Yt6JX-joKo

**Comment by yury** [comment]
Hello @muddi900,

Thank you for your report.
Yep, that is known issue with Full Keyboard Access. Please remap those shortcuts in Commands. 

Settings.app -> Accessibility -> Keyboards -> Full Keyboard Access -> Commands.

For instance, remap Activate (Space) to Shift Space.

I'm closing this issue, since we can't override Commands on our side. Feel free to reopen this issue if needed.
