### ISSUE TITLE
Stage manager support not working

### ISSUE THREAD

**Issue by deasmi** [blinksh/blink#1831]
### Checklist

- [X] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [X] Read the [docs](http://blink.sh/docs/)
- [X] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Describe the bug
Stage manager support seems utterly broken to my recent experience. Thankfully managed to get somewhat sanity back, but I shouldn't be able to get into this position.

Having just got an iPad Pro and plugged it into a screen I was looking forward to blink working nicely, it just doesn't.

Currently I have a black, not normal background color, rectangle on my ipad and a blink window on the external screen, which is full screen from an iPad perspective ( ie. no side icons ) but only using a rectangle of around 60% in the middle.

I cannot shut any windows, manage any windows, or otherwise try and fix this as when blink is in the foreground I can't even move the mouse to the external screen, it's bound to the iPad. The active blink window is on the external.

A reboot and re-connect of external screen seems to have reset this, but it's behaving as it should.

Changing to the 'stage' setting in Appearance now may have prevented a repeat, but people shouldn't be able to get into this mess. If stage manager is on, defaults need to change. 

Managable windows on both iPad and external display. Sane keyboard shortcuts to swap windows and sessions within windows.

Sadly could not get screenshots.

**Comment by deasmi** [comment]
No doubt related to #1748 and #1651

**Comment by deasmi** [comment]
Please excuse last two paragraphs they should have titles, I hadn't noticed the "Expected Behaviour" and "Screen shots" were comments and can't edit the issue now I've created.

**Comment by carloscabanero** [comment]
Hi! Sorry about that, it should have been set as the default, and I’m the one who in theory fixed that. I will double check what may be causing this.

By any chance, had you previously modified the External Display setting prior to this? The algorithm should set Stage as default (according to my tests) as long as the Appearance - External setting had not been set. Otherwise we respect that. 

In any case, the Stage setting should do the right thing for you.

Leaving here some notes. It is not an issue with device identification because the field was properly identified as Stage. I’m thinking we may be over complicating things with option here as no one uses the other selections. The defaults are usually the right way to go about this and I think will behave as expected in all cases. It is unclear who needed the other options other than “they were there”.

**Comment by deasmi** [comment]
This was the first time I'd used Blink with stage manager at all, and was really the first time I'd used stage manager in anger at all more generally.

Honestly this may be an edge case thing, I've not had any repeats of any issues, it's all behaving nicely now with 'stage' set in Appearance.

I am struggling to get it off the 'stage' appearance setting now, so can't really try and re-create the original issue till I've worked that out.

**Comment by carloscabanero** [comment]
Hi! Thanks again for the heads up. We have discovered why you found this situation in the first place, and got a fix so it does not happen again on first usage of the app :)

One question though, which was not clear from your previous message. Do you mean that if you set that option to anything else, the setting won't be saved? I was not able to replicate that.

**Comment by lucifer** [comment]
I've just got a new cable to support HDR on my LG monitor with an M2 and have the same 'external display' take over issue. I have 'more space' option on both screens and I find Blink does not persist any changes I make to Appearance > External Display. I'd for now just like it to not dominate my external screen at all but I cannot get this to happen without force quit and unplug display. Let me know if there is any. Troubleshooting I could do to help.

**Comment by carloscabanero** [comment]
@Lucifer so two things:
- Set the setting on Appearance > External Display to "Stage".
- **Press the "< Settings", back button so that changes are saved.** If you tap out and settings are closed without pressing back, they won't be saved.

After restarting Blink, then the regular Stage Manager should work and be set as-is.

**Comment by lucifer** [comment]
...so the options I have mention nothing about 'stage'
I only have Default Layout [Cover, Fit, Fill]
And External display [Scale, Inset, None, Mirror]

**Comment by carloscabanero** [comment]
@lucifer Select Mirror instead in that case. You said you have a M2 device. Looks like we did not detect it as an Mseries. Are you running the latest Blink version? What device is it?
