### ISSUE TITLE
option to not repaint on control+L

### ISSUE THREAD

**Issue by chetan-reddy** [blinksh/blink#192]
Hello. I work with a team which unfortunately prefers to use Control+L as their screen prefix key. When blink (or the default mosh-client in debian) see a Control+L they will perform a client side repaint,  even if the application running on the server handles Control+L differently. To fix this in debian, I had to rebuild mosh-client with the following one line change:
```
--- a/src/frontend/stmclient.cc
+++ b/src/frontend/stmclient.cc
@@ -375,7 +375,7 @@ bool STMClient::process_user_input( int fd )
       lf_entered = ( (the_byte == 0x0A) || (the_byte == 0x0D) ); /* LineFeed, Ctrl-J, '\n' or CarriageReturn, Ctrl-M, '\r' */
 
       if ( the_byte == 0x0C ) { /* Ctrl-L */
-       repaint_requested = true;
+       repaint_requested = false;
       }
 
       network->get_current_state().push_back( Parser::UserByte( the_byte ) );
```

Is it possible to do something similar in blink to make the Control+L behavior configurable? Thanks!

**Comment by carloscabanero** [comment]
Hi! It can definitely be changed in Blink too. You have two options: if you wanna do it yourself, you can change iosclient.cc file (which is basically a modified stmclient.cc) in our mosh branch, and build it with the build-mosh script, then just copy the generated library to the blink application folder; we can create a configuration from the app, although this might take longer.

I'm trying to figure out if Ctrl-L on Mosh triggering a repaint might be a wide assumption, and could make sense to fix it on Mosh too. I do not think it has an impact on the experience, maybe just a "flicker", but could you elaborate more what you guys are experiencing? Did you contact the Mosh project about  this before?

**Comment by chetreddy** [comment]
Thanks for the pointer. I will build it myself this weekend (i have to anyway since my free apple developer account causes requires a reinstall every 7 days).

You're right that it's just a flicker (and maybe an unnecessary network round-trip to get the 'latest' screen), but it gets annoying since the screen prefix key gets pressed often. I did ask about this in the mosh irc room a few years ago, and i recall them indicating the hack would work and not break anything.  Given this is a very unusual use case, I'll just rebuild with the change to iosclient.cc. Unfortunately, this means i cannot get the App Store version and will need to keep rebuilding every 7 days. If/when the option makes it to the App Store version, I'll purchase in a heartbeat. Thanks again for pointing me to iosclient.cc.

**Comment by yury** [comment]
I remapped Ctrl-L in iosclient to Ctrl-^ Ctrl-L.

@carloscabanero mosh changes are in ios-state state branch.

**Comment by yury** [comment]
I think we can close this.

**Comment by chetan-reddy** [comment]
I just tested that Ctrl+L doesn't repaint anymore. Thanks for fixing this @yury
