### ISSUE TITLE
Non-responsive black window after moving tab to new window

### ISSUE THREAD

**Issue by shlevy** [blinksh/blink#2001]
### Configuration

visionOS 1.1.1, Blink 17.3.0.873

### Describe the bug

I moved a tab to a new window, it showed up in the new window briefly and then the window went solid black and has been non-responsive since.

I was unable to reproduce this when trying again.

![IMG_0061](https://github.com/blinksh/blink/assets/487050/0ebb9811-27c2-45e0-acd1-74fc118e0043)

**Comment by mistakenideas** [comment]
I’ve seen this happen a few times in recent (17.3.0) builds too. I’m running iPadOS 17.3.1. 

Sometimes a blink shell tab will just become empty and unresponsive while others will remain/resume connectivity and functionality. This appears to happen when returning to the app/tab rather than during a session.

**Comment by carloscabanero** [comment]
So I'm moving this to 17.4.0. We have a new piece of interface coming up and the code that controls this may not exist anymore.

**Comment by mistakenideas** [comment]
At least for the issue I was seeing, it seems fixed in 17.3.0 (895) in Testflight. Likely as part of “Inactive SSH sessions return to the shell instead of hanging in the Tab”

**Comment by carloscabanero** [comment]
@shlevy are you still experiencing this from your side?

**Comment by shlevy** [comment]
Just tried and it worked fine, will let you know if it happens again.
