### ISSUE TITLE
Fatal Error Please check Developer Tools

### ISSUE THREAD

**Issue by 362228416** [blinksh/blink#2063]
I started a code tunnel on my Mac, and on another computer, I logged in with my GitHub account and connected to this channel 
normally without any problems. 

Now I use blink code on my iPad and connect to this channel through GitHub, but it prompts "Fatal Error Please check Developer Tools".

 I compiled this blink myself, and only modified the bundle id and developer team account, without modifying the code. Of course, because it needs to be compiled, the web-browser key must be removed from the info file. After this, there are no other modifications

 the compilation is normal, mosh can also be used normally, but code cannot be used. How can I solve this problem?

**Comment by 362228416** [comment]
My machine 

macbook pro m3 max

iPad pro（4）
OS 17.3.1

**Comment by carloscabanero** [comment]
I'm not sure `code` can work outside of Blink Shell. The problem is the entitlements are a limitation on iOS. Your browser is limited, and we got a special entitlement in Blink so that our browser is a real browser. If you are interested on contributing to Blink with more reports, etc... you can let me know and I can try to loop you in the Community version.
