### ISSUE TITLE
Allow specifying server port range in host configuration

### ISSUE THREAD

**Issue by xinan** [blinksh/blink#237]
Right now it is not possible to specify a port range for the `mosh-server` in the host configuration. I need that so that I can use a custom port range. With a single port, it would fail to connect if the app crashes because that port is occupied.

**Comment by carloscabanero** [comment]
Good point! Will do

**Comment by williamli** [comment]
I too would love to be able to allow port range to be selected since I have iCloud sync enabled and the port number is synced. That means I can only connect to 1 server from 1 iOS device at the same time.

**Comment by esaru** [comment]
+1 for specifying a range, and i get blocked by sessions which hang on client-side, but the work-around which i am using is to have multiple host profiles which differ only in their mosh port specification.

**Comment by downwith** [comment]
A simpler workaround for me was to just to put something like this in /usr/local/bin/mosh-server and point the host profile to that (instead of /usr/bin/mosh-server):
```sh  
#!/bin/sh -e

/usr/bin/mosh-server "$@" -p 60250:60499
```

In my case, I just needed to specify a custom range to allow for multiple servers through my firewall.  Understandably, it might not solve everyone’s needs.

**Comment by yury** [comment]
Current TF supports mosh port range in host configuration. See #881.
