### ISSUE TITLE
Ever considered Et?

### ISSUE THREAD

**Issue by chenglou** [blinksh/blink#293]
This isn't really an issue, but I wasn't sure where to ask this; feel free to close it!

My issue with mosh is the lack of truecolor (which blink has) and tmux control mode. Seems like this project has it: https://mistertea.github.io/EternalTCP/

I was wondering if it was ever considered for Blink.

Thanks for the great project!

**Comment by carloscabanero** [comment]
This is interesting, we should definitely keep an eye on it. A few things from the implementation that worry me are basically the “BackedReader” and “Writer”. Mosh basically just renders changes, they just seem to cache everything and that might provoke multiple problems. Plus security, Mosh isn’t resumable due to that sequence.

But definitely worth keeping an eye on.

**Comment by chenglou** [comment]
Feel free to close this issue btw. Apparently one design drawback is that it doesn't do optimistic rendering unlike mosh. cc @mistertea

**Comment by yury** [comment]
Closing in favor #597
