### ISSUE TITLE
Reconnecting to old sessions loses screen space

### ISSUE THREAD

**Issue by pbontrager** [blinksh/blink#295]
When I reconnect to a mosh session, a portion of the screen (bottom) is filled with dots and not useable. This seems to happen when I've used the app, it closes and I reconnect at a later point. The main screen is fine but as soon as I create a new mosh connection and I get this issue. I am using tmux but this issue doesn't seem to be exclusive to tmux panes. The only way to fix the issue seems to be to close the blink pane.

![img_0006](https://user-images.githubusercontent.com/6652398/27552659-3626576a-5a76-11e7-8a6e-4d2acb2d7210.PNG)

**Comment by goerz** [comment]
That's because there's another tmux client somewhere attached to the same tmux session. In my experience,  this can happen sometimes when the mosh client dies in a way that doesn't communicate to the mosh server to shut down. You can fix it by hitting `<tmux-prefix-key> D` to show all the connected tmux clients. You can select all extra clients there and press `Enter` to disconnect them, which will give you back your screen space.

In any case, this is not a Blink bug (except maybe to the extent that Blink leaves a mosh session hanging on the server)

**Comment by pbontrager** [comment]
This seems to be the case. Thank you. It would be nice to have the option to have the app end open mosh sessions if closed.
