### ISSUE TITLE
Reset iCloud saved Mosh port

### ISSUE THREAD

**Issue by joech4n** [blinksh/blink#333]
I'm getting this error:

blink> mosh a
Failed binding to 1.2.3.4:60000
Error binding to IP 1.2.3.4: bind: Address already in use
Failed binding to 0.0.0.0:60000
Error binding to any interface: bind: Address already in use
Network exception: bind: Address already in use
Did not find remote IP address
blink> 

and clearing the Mosh port in the config fixes the issue. However, the problem is that after some time, it repopulates with 60000. I do have iCloud sync enabled, so I wonder if that may be it. I've disabled it for now to test.

Any ideas why this is happening and what I can do about it?

Thanks for any help!

**Comment by DavidNielsen** [comment]
Since SSH still works I wrote a little Workflow to log on to my machine and run "killall mosh-server". Crude but effective. I'm sure there are better ways to work around this annoyance but this lets me click a satisfying button.

This betrays the promise of mosh, namely persistent connections but at least Blink remains more or less usable. It seems to be down to Blink, Termius does not display this issue on the same connection and mosh-server, it also retains connections as intended (that said their Mosh support is in beta). This does give me hope that Blink deliver though.

**Comment by carloscabanero** [comment]
Few things going on here:
- There seems to be a bug on iCloud because it seems to be repopulating the Port after removing it.
- If you initiate a new connection, mosh-client and Blink will both just connect to a new port, that is the expected behaviour. 
- We will work on #59 Persistent Connections to reconnect, but there are a few security concerns we are trying to solve in the best way possible.

I will keep this one open and rename as iCloud settings reset.

**Comment by zbeekman** [comment]
I think the iCloud portion of this issue may be a red herring. I have never enabled iCloud sync and the UDP port for my “work” host keeps getting repopulated even after clearing it. 

As a work around, I found that if I changed prediction to experimental and the back to adaptive after removing the text in the UDP port field that I could clear the UDP port and get it to stick

**Comment by martinweiss** [comment]
I have experienced the same problem, also without iCloud sync on.

**Comment by zywx** [comment]
Same here, also with iCloud sync on. any status?
