### ISSUE TITLE
No Password, Want to only use Key only

### ISSUE THREAD

**Issue by theseanodell** [blinksh/blink#335]
I have no password and require keys for authentication. What is the syntax for this to work properly? I keep getting prompted for a password.

I am sure I missed it somewhere but could not find it.

**Comment by QasimK** [comment]
In the hosts configuration, under SSH: leave the password field empty, and add a key to use instead

**Comment by theseanodell** [comment]
There is no way to leave the password blank. The "Ask Every Time" message is shown in grey in the Password field. I have selected a key. White out of the host and user name for obvious reasons.

![img_de0f8c97b83b-1](https://user-images.githubusercontent.com/9096060/29571029-c26173f8-871d-11e7-8d73-4cee5ed17b3d.jpeg)

**Comment by carloscabanero** [comment]
Hi! Sorry for the late reply. By default Blink always tries this:
- uses the configured key to access the server
- if that doesn’t work it will try with the id_rsa (so there is no need to set it up within the config), 
- if that doesn’t work then it will try to offer a configured password
- if that doesn’t work, then it will prompt the user

For some reason the key is either not installed within the server, or maybe the user trying to access doesn’t work. Do you have the key installed within the server?

**Comment by aegatlin** [comment]
I know I'm late to the party but I had the exact same problem and it turned out that when I _thought_ I copied the IP address into blink config, I had not and/or it did not save. Once I double checked and corrected it, I was able to log in. I had the ssh key already on the server etc

Basically, for me it was user error, and maybe some minor bug in saving host details
