### ISSUE TITLE
Possible bug with italics and strike through escape codes

### ISSUE THREAD

**Issue by BinaryBen** [blinksh/blink#37]
See the screenshot for test cases. Bold, underline, colors and combinations seem to work as expected. Italics and strike through are not working as far as I can tell.

Is this just a case of the included font doesn't actually have support for italics - therefore meaning that we can provide our own fonts with italics if we want them once that feature is enabled? Or is this a problem with the way the terminal emulator handles italic escape codes?

![image](https://cloud.githubusercontent.com/assets/12827556/16256387/69a9d1c6-3884-11e6-828e-386517d19679.png)

**Comment by carloscabanero** [comment]
Good catch! I would say this is because I did not add the italics on the current font because there was simply none in https://github.com/powerline/fonts repo. I do not have that problem on emacs though, but it might be doing some internal tricks. I'll mark as a bug and once I have enabled custom fonts, we will see how it goes. 👍

**Comment by BinaryBen** [comment]
When you say you don't have the problem with Emacs, do you mean it actually displays italics?

**Comment by carloscabanero** [comment]
Yup, I'd swear I saw it but cannot do it now. Maybe I just mixed stuff. I will keep an eye on this one :)

**Comment by carloscabanero** [comment]
This should work now. Closing.
