### ISSUE TITLE
Drag and drop TO Blink

### ISSUE THREAD

**Issue by carloscabanero** [blinksh/blink#408]
If you drag a bunch of text to Blink, it should be pasted to it.

**Comment by cwis-public** [comment]
+1

This would be awesome when logging in to servers that require One-Time Passwords. I am using 1Password, which allows for the OTP to be dragged, unfortunately since Blink is not a drop target I have to manually hit “Copy” and then “Paste” (or typing the characters by hand, which is way less user-friendly).

**Comment by yury** [comment]
http://www.youtube.com/watch?v=WwKTyFqeNdM
