### ISSUE TITLE
Clips?

### ISSUE THREAD

**Issue by dwest100** [blinksh/blink#465]
Hi,
Just purchased the app. I have several iPads in different locations. Is there some means to save frequently used command strings? If so, do they sync through iCloud? I can’t seem to find this functionality.
Thanks!

**Comment by carloscabanero** [comment]
Hi Don! You can save the Hosts and then sync them between devices through iCloud. To do that just type config on the shell to access the settings and create your hosts there. To enable iCloud, just flip the "iCloud sync" switch. Then on the rest of your devices just turn on iCloud switch and your hosts will start syncing. Within the terminal you will then have autocomplete which makes it easier to access them.

Hope that resolves your question and let us know otherwise ;)

**Comment by dwest100** [comment]
I did find that and thanks Carlos. I’m referring to saving frequently used “clips” or command line strings for reuse when needed. Is there any such capability in blink?

**Comment by carloscabanero** [comment]
Oh, sorry I misunderstood your question. Unfortunately we don't support that at the moment, but it would be a good feature, I will add it to the backlog. Thanks and sorry for the inconvenience.

**Comment by dwest100** [comment]
For reference, >Prompt2 by Panic,inc. has the feature if you need clarification of what I mean. Basically, provide a means to create a library of repeatable command strings, akin to bookmarks in a browser. Such that one could access the library, click on a clip, and the underlying command is transferred to the command line. As you know I’m sure, some commands get ridiculously long what with options and paths etc. This would save a ton of typing :)

**Comment by carloscabanero** [comment]
Yep, I saw that a while ago, but we didn't implement it as I never used it and Ctrl-R may be a substitute for that. In any case, we plan to have remote commands and I think this could fit very well with that.

**Comment by dwest100** [comment]
Sounds good, thanks again :)
