### ISSUE TITLE
Unicode prompt characters not rendering correctly

### ISSUE THREAD

**Issue by calvinhp** [blinksh/blink#472]
I’m loving blink, but there is one area that it isn’t handling correctly for my use case:

![09b2262e-be5b-452e-9361-daeb2bff7cdc](https://user-images.githubusercontent.com/157091/38342927-39b46b3a-384f-11e8-8cbf-c03b0e66c802.png)

This prompt comes from my dotfiles here: https://github.com/calvinhp/dotfiles/blob/master/.zshprompt

The Prompt client from Panic does display it correctly and I tried using the other fonts to see if that was the issue, but it always renders the same way.

It should look like this:

![362bb15e-65c5-4f52-a7b9-086f824ac38e](https://user-images.githubusercontent.com/157091/38343059-d53efc14-384f-11e8-8350-803b6c57f320.jpeg)

**Comment by yury** [comment]
Hi @calvinhp 

Can you post results of `locale` command?
Set locale to 'en_US.UTF-8' should help with that.

Sorry for late response.

**Comment by calvinhp** [comment]
Just got back around to this. I have my locale set to `en_US.UTF-8`, but I’m still seeing the strange characters. Here is the output from `locale`.

```
mq sfup-salt01%qq locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE=C
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=
```

**Comment by carloscabanero** [comment]
Configuration issue. Closing.

**Comment by calvinhp** [comment]
What is the configuration issue? Do I need to change a config?

**Comment by carloscabanero** [comment]
Yes! So this is a ncurses issue. Blink is a full UTF-8 terminal, and that although more modern, does not play well with the extended characters that were used back in the day for VT100 line-drawing with the ISO-2022. (https://chromium.googlesource.com/apps/libapps/+/master/nassh/doc/FAQ.md#why-do-curses-apps-display-x_q_etc_instead-of-and-and-other-graphics).

- The easiest way to solve this issue is to, instead of drawing characters in the old ISO-2022, just use UTF-8 characters in your script for the bar and all you need. Most of the applications after 25 years have finally migrated to UTF-8, so it may be time for our scripts to do it too ;)
- Another way to solve it is to tell ncurses that you are in a UTF-8 terminal, and to use the Unicode values that correspond to the drawing characters. You can do this by exporting NCURSES_NO_UTF8_ACS=1 somewhere in your .zshrc. (https://invisible-island.net/ncurses/man/ncurses.3x.html#h3-NCURSES_NO_UTF8_ACS)
- Another option is to change the terminal encoding on the fly. You can do that with `printf '\x1b%%@'`. You can actually run that in your shell in Blink, and see how it will immediately print the prompt the right way.
- And last option is to rely on a tmux or screen that will do the wrap for you.

**Comment by carloscabanero** [comment]
For your zshrc, I did the test and this would work:

PR_HBAR="─"
PR_VBAR="│"
PR_ULCORNER="┌"
PR_LLCORNER="└"
PR_LRCORNER="┘"
PR_URCORNER="┐"

I have no idea about what PR_SHIFT_IN SHIFT_OUT and all those do though, but you get the characters there.

**Comment by calvinhp** [comment]
let me give that a shot and thanks for the detailed follow up!

**Comment by calvinhp** [comment]
Works like a charm, sorry for the noise and thanks for helping me see what was wrong

**Comment by carloscabanero** [comment]
Thanks to you for sending the report. I think we should make this into the documentation too for future people, will tag it like that.
