### ISSUE TITLE
Dose blink support ssh config file?

### ISSUE THREAD

**Issue by zky999** [blinksh/blink#474]
Dose blink supports the ssh config file?  if dose, where should I put it and how can I "upload" the config file, as well as the private key to my iPhone?

**Comment by axot** [comment]
I also want to find how to upload the .ssh directory.

**Comment by yury** [comment]
Hi @axot,

You can't directly copy to .ssh folder from Files.app. But you can copy to local file system (Files.app -> On my iPad/iPhone/iPod -> Blink) or via iCloud Drive (Files.app or Finder -> iCloud Drive -> Blink).

Then you can use mv command to move your files to .ssh folder.

**Comment by mattrabe** [comment]
A little clarification for anyone doing this:

1. Copy a config file and/or ssh keys to your iOS device via Finder, etc on your Mac. In my case, I temporarily renamed my ~/.ssh folder to ~/ssh (because apparently Finder doesn't like copying things that start with a period to iOS devices) and then copied the whole thing to [My iPad]->Files->Blink using Finder.
2. In Blink, you should be able to `ls -l` and see the `ssh` folder you copied
3. Still in Blink, rename it: `mv ssh .ssh`
4. (Don't forget to un-rename your local folder if needed)

You should now be able to type things like `ssh host-from-config-file` and successfully connect to them. The hosts in the config file WILL NOT show up in the Blink Hosts menu. That last bit threw me for a loop for a minute...

**Comment by eun-ice** [comment]
I tried these methods with the new blink and they didn't work, I was not able to store a file in Files.app and read it in blink.

However, if you have the ssh config on a host you can ssh into, try this in blink:

```ssh user@host "cat .ssh/config" >.ssh/config```
