### ISSUE TITLE
Show keyboard shortcuts when holding command key

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#48]
Most iOS apps now show an overlay with the available keyboard shortcuts when the command-key on a hardware keyboard is held. Blink should do the same.

**Comment by carloscabanero** [comment]
The problem with that is that if you press the Cmd key a lot (and I know this first hand because for me it is mapped to Ctrl), then it is always on. We will offer the possibility to remap the shortcuts, so it will be a special section inside the config. Hope it is enough!

**Comment by BinaryBen** [comment]
I think issue #52 makes a good case for reserving ⌘ for system (iOS and Blink) shortcuts. Doing so would also allow this to be implemented, and would create a more "native" user experience. 

It would also make using the app more intuitive, as users would be able to just hold the ⌘ key, rather than have to invoke the help screen.

**Comment by yury** [comment]
PR #219  shows overlay on CMD

**Comment by carloscabanero** [comment]
Yup, pushed on v5.
