### ISSUE TITLE
Paste with command-v

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#52]
It would be great to be able to paste text with the `cmd-v` shortcut, instead of the cumbersome tap + paste.

I also seem to be unable to paste into a password prompt (e.g. from `sudo`)

It might be interesting to have a shortcut to for entering a "copy" mode (behaving similar to the feature in `tmux`), where text can be selected with the arrow keys, and then copied with the `cmd-c` shortcut.

In general, I feel like the standard iOS copy-and-paste functionality is much too fiddly in a terminal environment.

**Comment by Riprock** [comment]
It looks like Ctrl-v is pasting. This is a bit inconvenient for me as I need Ctrl-v for vim.

**Comment by goerz** [comment]
Yeah, I think Blink should involve `cmd` in all its keyboard shortcuts, so as not to clash with shortcuts of the programs inside the ssh/mosh session (vim and emacs pretty much cover all key of the keyboard, but never use `cmd`). Moreover, for pasting, `cmd+v` is the "standard" on iOS.

**Comment by carloscabanero** [comment]
PT #122617051

**Comment by BinaryBen** [comment]
Given that iOS has a few system wide shortcuts, most using ⌘ - I would also like to see Blink keep any and all keyboard shortcuts to use ⌘ as the leading key as well. 

+1 for ⌘-V remaining for pasting by default as well. 

I think this would allow for a "simple" limitation - don't use keyboard shortcuts using the "super" key on servers as they are reserved for iOS and blink. :)

**Comment by carloscabanero** [comment]
Ok, let's do cmd for all Blink / iOS shortcuts :) 

I will also add a switch / configuration for those like me who use Cmd as Ctrl, to choose what other key to assign it to.

**Comment by BinaryBen** [comment]
Legend! I think that will be a big boon for new users going forward, especially once launched on the App Store. And I love that you have no problem making the defaults customisable. :)

**Comment by carloscabanero** [comment]
- [ ] Create a section on keyboard settings for Blink Shortcuts trigger. By default it will be the Cmd key.
- [ ] Add shortcuts description section inside the "shortcut selection" screen.
- [ ] If Cmd is not used as a modifier, then trigger the "shortcuts" dialog on iOS, otherwise hide it - this can be achieved by not creating a description of the shortcut when creating the UIKeyCommand.
- [ ] Cmd + v to trigger paste action.
- [ ] Cmd + n to open a new space ' terminal.
- [ ] Cmd + [ and Cmd + ] to move between them.

**Comment by carloscabanero** [comment]
Done!
