### ISSUE TITLE
Unable to use ssh-copy-id

### ISSUE THREAD

**Issue by mcuix** [blinksh/blink#554]
I am unable to ssh-copy-id my ssh keys to my server.
I use 

> ssh-copy-id /.ssh/id_rsa.pub user@myserver

, but Blink returns an **ERROR no identity found**.

**Comment by yury** [comment]
Hi @mcuix,

‘ssh-copy-id’ command works only with keys from config->keys for now.

**Comment by JeremyIglehart** [comment]
Okay, it took me a while to figure this out because I couldn’t find any how to... maybe there is one somewhere and I overlooked it... if so, please feel free to point this out to us all.

Basically, I just installed Blink yesterday - my version comes with a generated key “id_rsa”.  Assuming you don’t change this key, or make a new one with a different name.  You could do something like:

```
ssh-copy-id id_rsa jeremy@192.168.10.10
```

Obviously you should use your username and host... but the ssh-copy-id is looking for the names of keys listed when you type config, and choose “keys” out of the menu.

Enjoy.

**Comment by ellierider** [comment]
> Hi @mcuix,
> 
> ‘ssh-copy-id’ command works only with keys from config->keys for now.

Can you please provide an example?

**Comment by carloscabanero** [comment]
There is more information here as well. The key is not a path but a key on your config > keys.

https://docs.blink.sh/basics/commands#ssh-copy-id
