### ISSUE TITLE
Option to disable vertical scrolling

### ISSUE THREAD

**Issue by nanzhong** [blinksh/blink#566]
I almost exclusively use blink to connect to a remote machine where I am running a terminal multiplexer. Having the ability to disable vertical scrolling would be really helpful in avoiding the unintended scrolling that happens when I want to use the mouse reporting of clicks that blink supports via tapping.

I think this feature would be a helpful addition.

**Comment by yury** [comment]
Hi @nanzhong,

What terminal multiplexer do you use? tmux or screen?

**Comment by nanzhong** [comment]
I use tmux.

**Comment by yury** [comment]
I know tmux better :), tmux sending special escape sequence that terminal supports mouse events. 
The main idea is to disable scroll in blink if terminal reported mouse events support. Not sure if it breaks some other apps. Will look on that.

**Comment by yury** [comment]
Or even better - forward scroll events directly to tmux

**Comment by goerz** [comment]
I'd much prefer disabling scrolling to forwarding forwarding scroll events to tmux.

**Comment by nanzhong** [comment]
I feel forwarding scroll events seems like the “expected” behaviour in terms of mouse event reporting.

@goerz how do you feel about forwarding scroll events by default with a configuration option to disable scrolling entirely?

I’m suggesting this without much knowledge of the underlynig implementation in blink, @yury would know better what is feasible.

**Comment by treyharris** [comment]
Summarizing from discussion in Discord with @yury for later reference:

Termux's handling of swipes in the view can be found at [this line](/termux/termux-app/blob/master/terminal-view/src/main/java/com/termux/view/TerminalView.java#L443).

It uses pseudo-mouse buttons 4 and 5 (which it has as constants `TerminalEmulator.MOUSE_WHEELUP_BUTTON` and `TerminalEmulator.MOUSE_WHEELDOWN_BUTTON`. As discussed in the [hterm docs](https://chromium.googlesource.com/apps/libapps/+/master/hterm/doc/ControlSequences.md#wheel-mice),
> No release events are generated.

Note, also, that in the following `else if`, it may fall back to arrow keys instead of buttons 4 and 5. This is discussed as the "Alternate Scroll Mode" in the [hterm docs here](https://chromium.googlesource.com/apps/libapps/+/master/hterm/doc/ControlSequences.md#alternate-scroll-mode). (For left and right scroll, this alternate scroll mode is the only way to do it, since there are no VT, xterm or ANSI controll codes for horizontal scroll "wheels" — up and down are encoded as buttons 4 and 5, but no provision is made for left and right "buttons".)

**Comment by NyaMisty** [comment]
It seems that #119 was the same thing

**Comment by yury** [comment]
We released Blink v13.4. It detects mosh/vim/tmux/emacs and stops scroll in favor of mouse wheel.

Closing this issue. Feel free to reopen if needed.
