### ISSUE TITLE
blink should remember the text size when restarting

### ISSUE THREAD

**Issue by strowger** [blinksh/blink#68]
Blink should remember what font size has been selected when it quits, and restart with the same.

Otherwise the user has to re-size manually, which can be tricky with slow links and/or if using a shared screen session with another device.

**Comment by goerz** [comment]
Also, cmd-0 should restore the "default" font size (which I assume will be configurable in the Appearance settings, once they are implemented)

**Comment by carloscabanero** [comment]
There is already Ctrl-+ - and 0 to restore; will change to command as we discussed before. Will implement  for release. Thanks!

**Comment by carloscabanero** [comment]
In case you have multiple shells, should it remember the size from last terminal?

There will be already a "default font size", that will evolve later in a "per host configuration". I think once we see how that works, we can come back to this and decide.

**Comment by carloscabanero** [comment]
@strowger, can you take a look at this scenario and let me know what you would expect from it? thanks!

**Comment by strowger** [comment]
Hi,

Thank you for this.

I very seldom have more than one session open at a time in blink.

If i open a new session, I would like the initial font size to be the same as the previous session.

When the app restarts, or the device reboots etc, I would like blink to open with the font size the same as the previous session was using. 

Obviously, an ideal for the future is that the entire session state is saved so that when the app restarts, the sessions are all resumed - but that's a separate issue.

If there were more then one session open when the app closed, this is obviously tricky if the sessions were using different sizes. The ideal, as you note, would be a "per-host configuration", in which sessions are opened using the default font size for the host/s in question.

For now, using *one* of the sizes that the previous sessions were using (perhaps ideally the last-used session) rather than the default (which is waaaay too big) would be a *huge* improvement.

Reasoning: 
When I open the app, reconnecting to my session is only 4 keystrokes: uparrow, enter, uparrow, enter - to get the mosh command from the blink command history and run it, and then on the destination host to get 'screen -d -r' from the history and run it. This feels slick and easy.

However, resizing blink's text to the correct size is clumsy and feels difficult. It's tricky to get the exact size that I had before, especially as there's currently no way for blink to show you exactly what font size/geometry you have. I sometimes have to ^A-x in screen to resize the session to fit the new window if I'm using a shared session, and some apps don't react well to this. 

Cheers

**Comment by carloscabanero** [comment]
Got it! I think profiles to configure the default font size as a start, and later per server, together with the geometry pop up will help on this. I will ping you once they are ready so you will decide when we can close this story :)



On Tue, Aug 23, 2016 at 4:15 AM -0400, "strowger" <notifications@github.com> wrote:












Hi,



Thank you for this.



I very seldom have more than one session open at a time in blink.



If i open a new session, I would like the initial font size to be the same as the previous session.



When the app restarts, or the device reboots etc, I would like blink to open with the font size the same as the previous session was using. 



Obviously, an ideal for the future is that the entire session state is saved so that when the app restarts, the sessions are all resumed - but that's a separate issue.



If there were more then one session open when the app closed, this is obviously tricky if the sessions were using different sizes. The ideal, as you note, would be a "per-host configuration", in which sessions are opened using the default font size for the host/s in question.



For now, using one of the sizes that the previous sessions were using (perhaps ideally the last-used session) rather than the default (which is waaaay too big) would be a huge improvement.



Reasoning: 

When I open the app, reconnecting to my session is only 4 keystrokes: uparrow, enter, uparrow, enter - to get the mosh command from the blink command history and run it, and then on the destination host to get 'screen -d -r' from the history and run it. This feels slick and easy.



However, resizing blink's text to the correct size is clumsy and feels difficult. It's tricky to get the exact size that I had before, especially as there's currently no way for blink to show you exactly what font size/geometry you have. I sometimes have to ^A-x in screen to resize the session to fit the new window if I'm using a shared session, and some apps don't react well to this. 



Cheers

**Comment by carloscabanero** [comment]
This is done on v0.1010!
