### ISSUE TITLE
Refocus on App Issue

### ISSUE THREAD

**Issue by Schr3da** [blinksh/blink#680]
Hey,

First of best ssh/mosh client. In general I made a switch from my macbook to an ipad pro as my goto on the road development tool. So remote server is a must :D However I sometimes use a external monitor as well and discovered once I leave the app and return than to the app again my typings do not work anymore on the external monitor however it works on the ipad screen so there must be some sync issue.

Unfortunatelly I totally switched to Linux as my real Computer (workstation) therefore Im unable to look for a fix myself and providing a pull request.

However maybe someone of the team got the time to look into it...

Steps to reproduce:

- Open blink  
- Open browser in split screen
- Tab on blink to „focus“ app
- connect a external monitor
- Blink should be visible on the external monitor
- Tab in the browser on the ipad screen (to „lose “  focus of blink)
- Tab in the blink split view on the ipad screen
- Key inputs are no longer shown on the external monitor (ipad screen continues working)

Kind regards
Schr3da

**Comment by ericboehs** [comment]
I literally just got the new iPad today and hooked it up to my external about an hour ago. I've been playing around with Blink and ran into this problem as well. I googled around and found some shortcuts for "Airplay mode" which work for externally connected montiors as well.

Press `Cmd+O` to toggle between your iPad's shell and your external display's shell. The focus isn't lost so much as you tapped your iPad to select the shell on your iPad. The real problem here is that you can't Cmd-Tab between slide over and full screen apps (something Apple hopefully fixes in iOS 13). 😢

Another shortcut that you might find useful is `Cmd+Shift+O` which will swap your iPad and external monitor's sessions.

**Comment by ericboehs** [comment]
You can also try this shortcut sequence for an (almost) touch-free Slide Over switcharoo:
1. `Cmd-Tab` to your Slide Over window and do your bidding.
2. `Cmd-H` to go to your home screen
3. `Cmd-Tab-Tab` (press Tab twice while holding Cmd) to get back to Blink

You should be focused on the external session now.

Another way to do the same thing:
1. `Cmd-Tab` to your Slide Over window and do your bidding.
2. `Cmd-Tab` to "select" Blink (this is where iOS falls down and doesn't focus the keyboard input)
3. `Cmd-H` to go to your home screen
4. `Cmd-Tab` to get back to Blink

**Comment by petermbenjamin** [comment]
I am running into the same issue, but I cannot seem to get the "workaround" working for me as described by @ericboehs .

**Comment by Schr3da** [comment]
Works now as expected!! Thanks a lot!!! 

@petermbenjamin hold down the Cmd button on your keyboard to get the list of available shortcuts. This might help you in addition.
