### ISSUE TITLE
Host settings are synced, but keys not -> refering unexistent key

### ISSUE THREAD

**Issue by botanicus** [blinksh/blink#688]
I have 2 iPads. Each uses different key.

Settings from iPad came from restoring all apps and settings from iCloud.

Now, if I change key for a host, it'll be instantly synced to the other iPad (over hand out?). Only that the other iPad doesn't have the key from the other one, because keys are not being synced.

As a workaround, I could just copy the other iPad's key, but I don't like that approach, I do want to have 1 key pair per machine.

**Comment by NightMachinary** [comment]
I actually like to sync my keys. Why isn’t that option provided?

**Comment by yury** [comment]
It is not secure to sync keys over iCloud

**Comment by carloscabanero** [comment]
We will soon have a way to securely perform this and we are looking for people who would like to try it. Let us know if you are interested!

**Comment by botanicus** [comment]
I'd be very happy to

**Comment by NightMachinary** [comment]
Why is it not secure?

**Comment by vpbxlgb** [comment]
Happy to test syncing keys.

**Comment by aalmenar** [comment]
This is the only thing im missing on the App. Will be happy to test it.

**Comment by NightMachinary** [comment]
This bug is rather grave for me; My keys keep changing to a non-existent key even though now I have iCloud sync active only on my iPad (the bad key comes from my iPhone settings). I am turning off iCloud sync on my iPad, too.

**Comment by carloscabanero** [comment]
Sharing keys over iCloud as-is would be insecure because your keys will end up on an iCloud backup. A possible option would be to do that only with keys that may contain passphrases, but I would seriously try to stay away from having sensible data on the Cloud as there is no way for you to even delete it from there at some point.

We are ready to test our integration with Bunkr app!! Bunkr securely stores your ssh key using secret sharing and it performs signatures using SMPC. The cool part is that your private key is never recomposed anywhere, none of the shares or nodes have access to your sensible data, and the device requesting your signature just obtains the final signature. This allows you to securely "share" the same key to multiple devices, or even to "share" temporarily if you wish to another computer or third party as they will never obtain the sensible material.

It can also be used for other things like storing plain-text secrets like API tokens that you may want to easily access within your servers or other sensible information like certificates, etc...

If any of you is interested, please send me an email to Carlos (at) bunkr.app. Thanks!!

**Comment by carloscabanero** [comment]
Fixed on #1712
