### ISSUE TITLE
Modifier keys wrt emacs

### ISSUE THREAD

**Issue by jra** [blinksh/blink#727]
### Ctrl(CapsLock)-Space: NOT WORKING
showkey -a (Blink logged into Linux) gives:
```
        32 0040 0x20
```
showkey -a (Apple Terminal logged into Linux) gives:
```
^@       0 0000 0x00
```
in emacs: get a space character, not set-mark-command command, i.e. "start selection"

### Ctrl(Ctrl)-Space: NOT WORKING
showkey -a (Blink) gives: `27 0033 0x1b` (brings up emoji on-screen keyboard)
in emacs: (brings up emoji on-screen keyboard)

### Alt(Cmd)-Ctrl(Capslock)->: NOT WORKING
showkey -a (Blink logged into Linux) gives:
```
        60 0074 0x3c
.       46 0056 0x2e
```
showkey -a (Apple Terminal logged into Linux) gives:
```
^[>     27 0033 0x1b
        62 0076 0x3e
```
in emacs: get a '.' character, not the end-of-buffer command (though, Alt-Ctrl-< works as expected)

### Alt(Cmd)-Ctrl(Capslock)->: WORKING (contrast with above)
showkey -a (Blink logged into Linux) gives:
```
^[<     27 0033 0x1b
        60 0074 0x3c
```
showkey -a (Apple Terminal logged into Linux) gives:
```
^[<     27 0033 0x1b
        60 0074 0x3c
```
in emacs: move to beginning of buffer, beginning-of-buffer command

### Ctrl(CapsLock)-[other characters]: WORKING
Those I tried and use most often seem to be working correctly.

### Blink Shell Settings
Settings > Keyboard
Modifier Keys:
Ctrl: Ctrl
Alt: Esc
Cmd: Esc
CapsLock: Ctrl
Special Keys:
<all off, defaulted>

### Hardware
iPhone 7
Apple Wireless Keyboard 2011
iOS 12.3
Blink Shell 12.8

**Comment by nanzhong** [comment]
Have you tried with `Grab Ctrl + Space` enabled?

**Comment by jra** [comment]
Thank you. That fixed:
Ctrl(CapsLock)-Space
Ctrl(Ctrl)-Space

Cmd as Esc works for most key combinations. It does not work for:
Alt(Cmd)-"$": in emacs: takes an iPhone screen shot, when it should ispell check.
Alt(Cmd)-">": in emacs: get ".", when it should put the cursor at the bottom of the buffer.

Using Alt as Alt seems to work for these combinations.

It seems like Cmd as Esc does not work when the shift key is also used.

**Comment by treyharris** [comment]
@jra I’m not entirely sure why this issue is still open. But for Emacs users it seems like the best combination of settings are

1. Modifier Mappings
   - **⌃ Ctrl:** Ctrl
   - **⌥ Alt:** Esc
   - **⌘ Cmd:** None
   - **⇪ CapsLock:** None

1. Special Keys
   - Toggles: all *off,* except **Grab Ctrl+Space**
   - **Function Keys:** ⌘ + ⇧ Shift + number
   - **Cursor Keys:** ⌘ Cmd + arrow _(optional, may mess with some’s Emacs configs)_

1. Blink Shortcuts, **Shortcuts:* ⌘ Cmd + key

Finally, **“Smart Keys” → “Show with external keyboard”** should be toggled *on* for pressing Esc in isolation.

**Comment by yury** [comment]
Ctrl-space is working again. Closing this issue. Feel free to reopen if needed.
