### ISSUE TITLE
Swipe for arrow keys?

### ISSUE THREAD

**Issue by nickwanninger** [blinksh/blink#786]
Is it possible to optionally replace the swiping gestures with arrow keys like how terminus has? Basically pressing and swiping sends the directional arrow key at different speeds based on how far you swipe. 

Or even better, sending the mouse codes for scrolling instead of arrow keys

**Comment by yury** [comment]
Hi, @nickwanninger. 

We already report taps as mouse clicks. And we plan to report scrolls too. We are working on new [Smart Keyboard](https://youtu.be/0iJtQA78YvE)

What do you think, will it work for?

**Comment by nickwanninger** [comment]
Yeah that would work really well

**Comment by jmeosbn** [comment]
@yuri can I please ask how to get shell (remote zsh/bash and local blink) to accept this mouse codes? They're awesome in nano etc, and macOS is able to do this to shell as well as just curses apps..

**Comment by yury** [comment]
not sure zsh/bash can handle scrolls by them selves.. I use tmux for that.

**Comment by jmeosbn** [comment]
Ah, I meant for positioning cursor - would be great to just tap where I want to be (like in nano) rather than using e.g. Esc-B etc. (perhaps many times) followed by arrow cursors just to change a character in the middle of a path name*. I know bash/zsh accept this in macos by using Alt-click so I assume it receives a mouse code? Unless macOS is doing some work around using regular cursor navigation.

> (* while there are history replacements, ^R and Esc# etc. that are a bit quicker - though have more mental load and most don't know of - I at least, end up using the traditional cursor navigation in most cases)

**Comment by jmeosbn** [comment]
Also, while I've been trying to get used to the swipe keys, the one thing I find lacking is being able to quickly tap (repeatedly) arrow keys rather than the new swipe (and hold) (though slowing the repeat rate should help, a single tap is way more comfortable).

My idea is that this is really only a big issue for left/right positioning (such as on the command line or in nano etc. which is way more used than up/dn) and up and down swipes seem more natural wrist movement  than left/right.

So could we regain two tappable left/right arrows, that also retain up / left swipe functionality (consistent which the dual use smart keys) on left arrow key and the equivalent for right arrow?

Would only be one extra key to restore most of what was good about the previous buttons. 😎
